### ISSUE TITLE
Rename Save to Overwrite

### ISSUE THREAD

**Issue by madduck** [jeromerobert/pdfarranger#100]
There is "save" and "save as", the latter of which requires me to specify a (new) filename. The former, however, also pops up a dialog, and in order to save the file I was just editing, it requires me to click on it, and then confirm that I want to replace the file.

Please make "save" just save the current buffer to the same file it was loaded from, as if I was editing the file with any other editor that also has "save" and "save as".

**Comment by jeromerobert** [comment]
I won't. See #65 for the reason.

Would it be clearer if I replace "Save" by "Overwrite" ?

**Comment by madduck** [comment]
You could even make it "Overwrite firstfile.pdf" in the menu. If the menu item then overwrites the file without a file chooser dialog, though possibly asking for confirmation (with a tickbox "do not ask for confirmation in the future"), then that would be awesome.

**Comment by jeromerobert** [comment]
Thanks to changes in the window title (0664b72, 065e72b) it's now clear that pdfarranger is not an open/save application. It's even possible to save and empty document. The logic is that you start with an empty document where you insert new pages. I don't plan to add an other logic for single document scenario.

Document properties, table of content, encryption make that even more true.

So I'm closing that issue.
