### ISSUE TITLE
Filetype: "application/wps-office.pdf" not supported! (Ubuntu)

### ISSUE THREAD

**Issue by ftharyanto** [jeromerobert/pdfarranger#101]
![image](https://user-images.githubusercontent.com/17604130/62773848-379c3180-bade-11e9-93ef-71822f491b07.png)

OS: Ubuntu 19.10
PDF Arranger version 1.3.0

When I tried to open pdf, it failed and showing error message like in the picture. After I uninstall WPS, the PDF Arranger runs normally and could do the task. Is this bug could be fixed?

**Comment by jeromerobert** [comment]
Could you give the output of `mimetype -D -a anypdffile.pdf` when WPS is installed?

**Comment by jeromerobert** [comment]
Nevermind. I think it's useless to test the MIME type before opening a file. *pdfarranger* should try to always open the file (with Poppler). If this is not a PDF file it will raise a [`GLib.Error`](https://lazka.github.io/pgi-docs/#GLib-2.0/classes/Error.html#GLib.Error) with `domain=poppler-quark`, `code=4` and `message=PDF document is damaged`. I should just replace the message by `File is not a PDF document or is damaged`.

**Comment by mimi89999** [comment]
Actually, is it OK to just change the MIME map like that? It doesn't seem so to me. Other people are also having this issue: https://askubuntu.com/questions/1171311/chrome-doest-recognize-pdf-files

It also isn't listed on IANA: https://www.iana.org/assignments/media-types/media-types.xhtml

I think that this is actually an issue with WPS and pdfarranger should continue to check the MIME.

**Comment by jeromerobert** [comment]
Ok the bug was in WPS Office not pdfarranger. Let's reuse `mimetypes`.
