### ISSUE TITLE
Arch packages are missing the Poppler dependency

### ISSUE THREAD

**Issue by nortexoid** [jeromerobert/pdfarranger#103]
Using both the git package from AUR and the one in the community repos returns the following after a recent update:

(pdfarranger:10356): Gtk-WARNING **: 09:35:23.979: Theme parsing error: gtk.css:127:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(pdfarranger:10356): Gtk-WARNING **: 09:35:23.979: Theme parsing error: gtk.css:128:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(pdfarranger:10356): Gtk-WARNING **: 09:35:23.979: Theme parsing error: gtk.css:132:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
Traceback (most recent call last):
  File "/usr/bin/pdfarranger", line 11, in <module>
    load_entry_point('pdfarranger==1.3.0', 'console_scripts', 'pdfarranger')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/pdfarranger/pdfarranger.py", line 91, in <module>
    gi.require_version('Poppler', '0.18')
  File "/usr/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Poppler not available

**Comment by jeromerobert** [comment]
You are missing the `poppler-glib` package. It looks like:
* https://www.archlinux.org/packages/community/any/pdfarranger
* https://aur.archlinux.org/packages/pdfarranger-git

does not declare this dependency. I suggest you report this issue to the Arch packagers.

**Comment by nortexoid** [comment]
Cheers, that worked! I think they didn't require it as a dependency because it wasn't previously needed--at least, pdfarranger worked without having had that package installed.
I'll try to report it to the Arch packagers.

**Comment by jeromerobert** [comment]
It has always been needed even when it was called pdfshuffler. More likely you had `poppler-glib` because of an other application so you did not notice the issue before.
