### ISSUE TITLE
Idea: Insert pages of a PDF at drop location

### ISSUE THREAD

**Issue by dreua** [jeromerobert/pdfarranger#106]
Currently when dropping a pdf file on pdfarranger, all pages are inserted at the end. I think the user experience might be better with the pages inserted at the drop location. This is already possible when moving a selection of pages from one pdfarranger instance to another, so I believe it shouldn't be to hard to do it for pdf files as well.
I will wait for feedback before I might start working on this.

**Comment by jeromerobert** [comment]
In that case, the `Gtk.IconView` does not show a cursor where the drop should happen but it does not matter.  `iconview.get_dest_item_at_pos(x, y)` does work so I agree that it should be easy to implement. It's about of mimic `iv_dnd_received_data` in `sw_dnd_received_data`.

**Comment by dreua** [comment]
> In that case, the `Gtk.IconView` does not show a cursor

Do you know why that is the case? Is is just not possible if the drag event comes from another window or is it somewhere in the code? 
I would also love to have a better user experience with drag and drop in general, because quite often the drop location is one off the point that I was expecting. I'm thinking about moving the existing pages slightly out of the way (maybe animated) to signal the current drop location. I have no idea though, whether this is possible or how much work it would be, need some research on that.

**Comment by jeromerobert** [comment]
> Do you know why that is the case?

Sadly, I don't know. But as a starting point I would look for `GTK_IS_TREE_DRAG_SOURCE` in https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gtk/gtkiconview.c. May be also:

<https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/TreeDragDest.html#Gtk.TreeDragDest.row_drop_possible>

is involved (https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gtk/gtktreednd.c).

> Is is just not possible if the drag event comes from another window or is it somewhere in the code?

It's the default GTK behavior when the source of the drag is not a Gtk tree (whatever it is in the current process or not). I don't know if that can be changed. Comments in <https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gtk/gtktreednd.c> tend to say it is.

**Comment by jeromerobert** [comment]
Done by kbengs at c807a86 and d420186.
