### ISSUE TITLE
After "export selection" save overwrites the exported file

### ISSUE THREAD

**Issue by dreua** [jeromerobert/pdfarranger#108]
Steps to reproduce:
- Load a PDF into pdfarranger
- Select one or more (but not all) pages
- "Export selection", choose name, e.g. "testExport.pdf"
- "Save"

Expected behavior: 
- "Save" opens a dialog to choose a file name.
- "testExport.pdf" contains only the previously selected pages

Current behavior: 
- "testExport.pdf" is overwritten and contains all the pages

As always: I might fix this myself as I get the time. Until then, I like to document it here. (I hope, you don't mind.) Of course I'm also happy if some else does the fixing.

**Comment by jeromerobert** [comment]
```
