### ISSUE TITLE
Merge windows branch

### ISSUE THREAD

**Issue by htgoebel** [jeromerobert/pdfarranger#11]
I'v seen, there is a branch called "windows". Please merge this into master if possible and state that windows is supported, too. Thanks.

**Comment by jeromerobert** [comment]
No it's too old and too different from the master branch. By the way pygtk is supposed to be portable to Windows. So to let this topic progress I suggest that those who want to have pdfshuffler on windows test it as it is and report bugs about what does not work.

Reading the windows branch code I don't see how it is related to a Windows port. I don't know what Konstantinos had in mind when he made it.

**Comment by jeromerobert** [comment]
As @carlos22 did some work on that topic I reopen the issue. I'll test his branch and merge it.

https://github.com/carlos22/pdfshuffler/commits/master

**Comment by carlos22** [comment]
Yes it works but still has some TODOs, see: https://github.com/carlos22/pdfshuffler/blob/master/Win32.md#todo
The main drawback is the missing cleanup of the temp files. Windows has some kind of weird locking going on - the old windows version had some code to work around that. Currently it delete just fails but does not break the app.

**Comment by jeromerobert** [comment]
* 82577c8
* a6b1f37

To be continued at #19 and #23
