### ISSUE TITLE
unsupported operand type(s) for *: 'float' and 'Decimal' when cropping a pdf file

### ISSUE THREAD

**Issue by Npa972** [jeromerobert/pdfarranger#112]
After cropping a pdf file, the new file can't be saved : unsupported operand type(s) for *: 'float' and 'Decimal'
This file is a scan in pdf format (single page with simple-scan).
I tried today with a "regular" pdf and cropping works fine.

**Comment by jeromerobert** [comment]
Which version of pdfarranger is it ?

**Comment by jeromerobert** [comment]
I think it's already fixed in d444ffc

**Comment by Npa972** [comment]
Thank you !
Version 1.3.0-2 (2019/08/24)
