### ISSUE TITLE
Rotate doesn't work on Windows

### ISSUE THREAD

**Issue by filippobottega** [jeromerobert/pdfarranger#113]
Hello!
I have rotated some pages of a PDF using Windows version of pdfarranger.
I have saved the resulting set of pages to a new file but when I open the new file the pages are not rotated.

Best regards,
Filippo

**Comment by jeromerobert** [comment]
Could you provide the culprit PDF file so I could reproduce the issue ?

**Comment by jeromerobert** [comment]
Could you confirm that it's with pdfarranger 1.3.1 ?

**Comment by filippobottega** [comment]
Hello,
  I'm using pdfarranger 1.3.1. I have discovered that rotation works well except in one case with a file with PDF version 1.4. I have converted the file to PDF version 1.7 and now I'm able to rotate and save pages correctly.
  I'm sorry but I can't send you the original file because sensitive info inside.

  Thank you for your feedback.

  I'll close the issue.

  Best regards,
    Filippo.
