### ISSUE TITLE
Clean up warnings (many unused variables)

### ISSUE THREAD

**Issue by dreua** [jeromerobert/pdfarranger#115]
I'm thinking about fixing all the warnings PyCharm highlights in the default setting and maybe also those from Codacy while I'm at it. That would mean prefixing many unused arguments and some variables (when unpacking tuples, they are unused but still needed) with an underscore. How do you think about this @jeromerobert ?

**Comment by jeromerobert** [comment]
IMHO the common way to name unused variables is `_`. When `_` is reserved for gettext `__`is the way to go. Ref: https://docs.python-guide.org/writing/style/#create-an-ignored-variable. What does pycharm think about `__` ?

That was on my todo list so I'm glad that you are thinking about it.

**Comment by dreua** [comment]
Problem with __ is that in many cases there is more than one unused parameter (all the Gtk stuff) and you can use __ only once per functon. That's why I was thinking about _something instead. It might come in handy that this way some information about that parameter is preserved in case it should be needed in the future.

Another source of warnings is `Instance attribute {config, uiXML, ...} defined outside __init__`. Should we create an __init__ function with all the attribute definitions? I would check if it is possible to move some of the initialization code there as well, but I don't hold my breath.

**Comment by jeromerobert** [comment]
Ok I missed that point. So let's go with `_something`. I hope that Codacy will like it.

Yes, I also think that it should be better to move attribute definitions to `__init__`.

**Comment by jeromerobert** [comment]
Closed by ceb730b
