### ISSUE TITLE
Feature Request: Remember previous crop input values

### ISSUE THREAD

**Issue by dCo3lh0** [jeromerobert/pdfarranger#118]
one of the things i miss the most from pdf shuffler is that it remembers the input i previously put to crop a file, if i want to crop 20% of the top, 4% of the bottom, i and clicked ok, if i want to correct and place 21% at the top, i need to input all values on all boxes again, it would be great if pdf arranger could remember the previous input values too.

**Comment by dreua** [comment]
If it worked in pdfshuffler then it's more likely a bug than a missing feature. Will look into it, thanks for reporting!

**Comment by dreua** [comment]
Unfortunately I can't reproduce the problem. When I select a page, crop it and then open the crop dialog for the same page again, the fields are filled with what I previously entered for that page. Is that not working for you? Are the boxes empty or filled with 0?
It could be helpful to know your operating system, it's version, pdfarrangers version and how you installed it. If possible, try running pdfarranger from the command line and check for output.

**Comment by dCo3lh0** [comment]
filled with 0, it doesn't hold up the previous values you input to visualize the cropping area, if i need to change, i must remember with precision every value that was put before i tried to change it.
My OS is Linux Mint 19.2 and my DE is XFCE, my pdfarranger version is 1.3.1, i have installed from a ppa from LinuxUprising

The steps are: 
    Open pdf file
    place crop values and click ok
    try to change it, to increase or reduce a size and value is 0 in all areas

**Comment by dreua** [comment]
I have no clue why or under what circumstances this happens but fortunately when I made a minimal example I got that deprecation message: 

`PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "value" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.adjustment = Gtk.Adjustment(42, lower=0, upper=100, step_increment=1, page_increment=10, page_size=5)
`

And following that advice fixed the problem.

**Comment by dreua** [comment]
Here is my [minimal example](https://gist.github.com/dreua/868cfb4b61f64e6d613d6a8f0e08dd26). I would be glad if someone could take this and report it as I currently don't know where that would be.
It should give display two SpinButtons both pre-filled with 42.

My findings so far:
Fedora 30, Gnome, x11 ->  42 | 42 :heavy_check_mark:
Console output:
```
Installed GTK+ version is 3.24.11
/home/da/git/pdfarranger/pdfarranger/testspinbutton.py:20: PyGTKDeprecationWarning: Using positional arguments with the GObject constructor has been deprecated. Please specify keyword(s) for "value, lower, upper, step_increment, page_increment, page_size" or use a class specific constructor. See: https://wiki.gnome.org/PyGObject/InitializerDeprecations
  self.adjustment_depr = Gtk.Adjustment(42, 0, 100, 1, 10, 5)
```

Linux Mint 19.2, Xfce, x11 -> 42 | 0 :x: 
Console output:
`Installed GTK+ version is 3.22.30`
