### ISSUE TITLE
Rotation of pages isn't saved

### ISSUE THREAD

**Issue by ksmolder** [jeromerobert/pdfarranger#120]
# How to reproduce
1. Using `pdfarranger` 1.3.1 on Ubuntu 18.04 (installed via PPA) with `pikepdf` installed via pip3
1. Open PDF file
1. Rotate one or more pages
1. Save, Save as... or Export the adjusted PDF

# What I expect
1. The new PDF file contains the rotated pages

# What I actually see
1. Rotation of pages is not saved into the new PDF file

**Comment by jeromerobert** [comment]
Could you provide a PDF file which allow to reproduce the problem ?

**Comment by jeromerobert** [comment]
May be the same as #113 which we didn't have the opportunity to investigate.

**Comment by ksmolder** [comment]
Had a look at #113. The PDF I had issues with is indeed a version 1.4 file. I tried it with a more recent file (1.6.5) and that one seems to work.
I also installed PDF Shuffler in order to see of this issue is longer present. But PDF Shuffler was able to rotate and save the file.

**Comment by jeromerobert** [comment]
PDF Shuffler is using PyPDF2, not pikepdf. If you uninstall pikepdf, pdfarranger will fallback to PyPDF2 and rotate should work. But I would really fix that bug (even if it's probably in qpdf and not in pikepdf nor pdfarranger), so I would be glad to have a PDF file.

**Comment by ksmolder** [comment]
I've attached two files:
* "rotate - works.pdf" is a PDF v1.4 file generated with Inkscape. Saving an applied rotation works in PDF Arranger.
* "rotate - broken.pdf" is a PDF v1.4 file generated with Xerox scanner. Saving an applied rotation fails in PDF Arranger.

[rotate - broken.pdf](https://github.com/jeromerobert/pdfarranger/files/3751177/rotate.-.broken.pdf)
[rotate - works.pdf](https://github.com/jeromerobert/pdfarranger/files/3751179/rotate.-.works.pdf)
