### ISSUE TITLE
Cropping doesn't work correctly on the first page

### ISSUE THREAD

**Issue by lostgeek** [jeromerobert/pdfarranger#129]
Steps:
1. Load in PDF
2. Select all pages
3. Use crop function
4. Save new PDF

Bug:
The first page will be cropped in a different manner than all the other pages.

**Comment by jeromerobert** [comment]
I cannot reproduce that. Could you please provide the version used and a PDF file which allow to reproduce the bug.

**Comment by lostgeek** [comment]
Funnily enough I also couldn't reproduce it with most of my pdf files. Just the ones that come out of our Ricoh scanner seem to have this problem.

[problematic.pdf](https://github.com/jeromerobert/pdfarranger/files/4138629/problematic.pdf)

I'm using the latest 1.4.0 version.

**Comment by jeromerobert** [comment]
Hum, I still cannot reproduce it. Which version of PikePDF do you use ?

**Comment by lostgeek** [comment]
I'm on Arch Linux.
pdfarranger: 1.4.0-1
python-pikepdf: 1.10.0-1

This is what I get when I try to crop 50% on the right on all pages: 
[result.pdf](https://github.com/jeromerobert/pdfarranger/files/4142421/result.pdf)

**Comment by jeromerobert** [comment]
I reproduce the bug, thanks.
