### ISSUE TITLE
[Regression] Error when trying to save duplicated pages

### ISSUE THREAD

**Issue by dreua** [jeromerobert/pdfarranger#134]
[Fedora user norbertj reported this testing the update to 1.4.0](https://bodhi.fedoraproject.org/updates/FEDORA-2020-c73638803c)
> Works mostly, but when I duplicate a page (either by drag&drop or the new duplicate function) and try to save, message "empty PDF (page 1 (numbered from zero): object 3 0): duplicate page reference found; this would cause loss of data" appears. With PDF Arranger 1.3.1 this worked, probably because I used that with PyPDF2 rather than pikepdf.

I reproduced this issue with different PDFs - all had the described result. It also happens when using the new "Split pages" function (makes sense since this is essentially duplicating and cropping).

![Screenshot from 2020-02-02 12-10-14](https://user-images.githubusercontent.com/15114715/73656326-31070500-4690-11ea-81f8-6f92b03686e7.png)
Console output from a different run:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pdfarranger/pdfarranger.py", line 638, in choose_export_pdf_name
    self.save(only_selected, file_out)
  File "/usr/lib/python3.7/site-packages/pdfarranger/pdfarranger.py", line 195, in wrapper
    func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pdfarranger/pdfarranger.py", line 680, in save
    exporter.export(self.pdfqueue, to_export, file_out, m)
  File "/usr/lib/python3.7/site-packages/pdfarranger/exporter.py", line 58, in export
    pdf_output.pages.append(current_page)
pikepdf._qpdf.PdfError: empty PDF (page 5 (numbered from zero): object 3 0): duplicate page reference found; this would cause loss of data
```

**Comment by dreua** [comment]
Working on a fix... This looks promising: https://github.com/pikepdf/pikepdf/issues/60#issuecomment-546581251

**Comment by dreua** [comment]
Okay, that was quite easy
@jeromerobert I would like to get the fixed version into Fedora, essentially skipping 1.4.0 there. I could patch it downstream but if you are planning to release a bugfix 1.4.1 in the next couple of days that would be easier for me, how do you think about that?

**Comment by jeromerobert** [comment]
@dreua Yep, I do plan a 1.4.1 soon.

**Comment by dreua** [comment]
That's great news! I think I got a workaround for #130 that should be ready tonight. I don't know when "soon" will be, so just in case you want to wait for that.

**Comment by jeromerobert** [comment]
"Soon" might be next week-end. I will wait for #130.
