### ISSUE TITLE
Add continous integration for pip install

### ISSUE THREAD

**Issue by jeromerobert** [jeromerobert/pdfarranger#139]
As mentioned in #128 we need continuous integration. We already have Codacy which should detect all syntax errors but it does not look at gettext files (po files). Moreover it should be possible to test the whole `pip install` process.

I don't have any plan for CI for pdfarranger it self. I think the best testing framework would be [Dogtail](https://gitlab.com/dogtail/dogtail) but it would be too much work for me.

I already used Travis which has been the most popular for a while. CircleCI appear to be also often used on Github. But now that Github provide it's own CI solution, namely [Github Actions](https://github.com/features/actions), I'm going to give it a try.

**Comment by dreua** [comment]
Where would you need help the most? Writing Dogtail tests? Making them run automatically? How would the dogtail tests work when implementing #87 and which one should be first priority? 

Ideally we would also have a way to compare produced PDFs with known-good results, but that's probably going further than your current plans.

Thinking about #105 or #106, test driven development would definitely save some clicking, not only when testing the new behaviour but also making sure there are no unwanted side effects.

**Comment by jeromerobert** [comment]
> Writing Dogtail tests?

Yes, writing and even more, maintaining them when pdfarranger change. UI automatic testing is really a nightmare, unless you have an army of guys to do it.

> Making them run automatically?

No that should be easy

> How would the dogtail tests work when implementing #87 and which one should be first priority?

#87 has a higher priority than dogtail. If someone write dogtail tests for the current version of pdfarranger, he probably would have to rewrite them entirely for the new UI look & feel. I don't know how dogtail will work with GTK 4.

> Ideally we would also have a way to compare produced PDFs with known-good results, but that's > probably going further than your current plans.

I think it's not the most difficult part. We can convert PDF to text and diff the text. We can also convert each PDF file to images and use imagemagick's compare. But I don't think we'll ever reach that point because we will stay stuck on writting dogtail tests.

**Comment by dreua** [comment]
> We can convert PDF to text and diff the text.

I was thinking about that too, but I dismissed the idea because it won't find issues with rotate / crop. I believe that pikepdf or qpdf should have some automated test, maybe we can get some inspiration there.

So for the roadmap that sound like #87 is the way to go and then add dogtail tests there.
