### ISSUE TITLE
cut/copy/past actions

### ISSUE THREAD

**Issue by kbengs** [jeromerobert/pdfarranger#140]
Would be nice to have option to cut / paste selected pages when right clicking. It is now a bit hard to move for example the last page to the beginning when there is a lot of pages..

**Comment by jeromerobert** [comment]
Yep, this was on my (hidden) to do list.

The problem is not that we don't have cut/copy/paste actions in the menu, the problem is that we don't have them at all. The current drag & drop must be reimplemented to separate the drag & drop behavior from the cut/copy/paste code, so it could be reused in menus (and have ctrl+cxv shortcuts).

It would also make #67 easier to implement.

**Comment by dreua** [comment]
Before thinking about code I see a UX problem here: We currently do not have a cursor *between* two pages but only a selection of pages. Think of text editing: The cursor is usually not *on* but *between* two characters and you can move it in front of the first and after the last character. We could decide to paste pages before or after the current selection but either way it wouldn't be possible to paste as the first and the last page.

**Comment by jeromerobert** [comment]
As I'm not that comfortable with UX I was thinking to something like:

* A *past* action (either before or after but not both) which would be bound to `ctrl+v`
* A *special past* action which would manage before, after, and interleave (for #67)

I don't know yet if special past should popup a dialog or be split into different actions (into a submenu).

**Comment by kbengs** [comment]
One way of doing it using partly already available functions (I suppose) would be first to do a modified version of the "export selection" that would save selected pages to temporary location (without having to supply a place and file location). Then delete selected pages. Then you would select the page where you would like to paste. Then choose "paste", and it would paste for example after selected page.

Another thing a bit related to this, I would suggest in pdfarranger.py on line 853 "autoscroll_area = 40" would be increased to 80.

**Comment by kbengs** [comment]
I have been working on this. If someone wants to see it is in kbengs/pdfarranger/kben/raw fork/branch. It paste after selected item(s) (after last selected item). Paste to other instance does not work. But otherwise it seems to work. Should I continue or stop? :)

**Comment by dreua** [comment]
I just gave it a try and it definitely feels like a good addition! :+1:  Like I mentioned before we now have the problem, that you can't paste something before the first page. I wonder if we could add a selectable dummy before the first page that could be selected by arrow buttons or clicking so that pages pasted there would end up at the beginning. (I may be aiming high here, a "paste before" action would be probably easier to implement and sufficiently usable when mapped to Ctrl+Shift+V.)

For allowing copy and paste between instances you could serialize all the data to a string and put that in the actual clipboard, similar to the current implementation of drag and drop. Like Jerome already mentioned, the current drag and drop code should be reused in that case. (And it probably needs some refactoring beforehand.)

**Comment by kbengs** [comment]
Ok, thanks for comments. I have done more changes now:
-added "Paste special" menu item. It includes "Paste before" item. (so that we maybe could add "paste interleaved" to it later)
-added ctrl + shift + v for paste before
-added cut, copy, paste and clear functions that also drag and drop uses. "dnd intern" is unchanged, as it works very differently.
-drag to empty instance also possible
-clipboard uses Gtk.Clipboard

Dont know of any problem with it. Not tested anything on windows.

**Comment by jeromerobert** [comment]
* There are some noisy/useless changes in `pdfarranger.ui` which should be removed (probably a Glade side effect)
* `self.cb` is too short for a such large scope variable. self.clipboard would be better.
* May be I'm wrong but I think that the `on_action_copy` function should not `set_unsaved` nor update the undo manager as it does not modify the data.
* Refactoring/factorization with drag/drop is still to be made but there are already a lot of changes here, so it could be done in a second time (and by someone else). But if you want to make it in the same PR (which is also fine), please keep in separate commits.
* Try to reorganize your branch before raising a PR. It should reflect the changes you provide, not the errors and trials you made to achieve this changes. Currently I have to squash all your commit to a single one to be able to read what you want to contribute. It will also help you to find better commit messages. `git rebase -i`, `git gui`, `git crecord` are some of the commands you may find useful to reorganize your branch.
* I don't plan to merge this before 1.4.2 has it's too disruptive for bug fix release. It will be for 1.5.0.

**Comment by kbengs** [comment]
Thanks for comments. I have cleaned the history and fixed the things you commented. It is now in kben/cutcopypaste branch. If/when I feel I have no more to add to this, is it too early to make a PR, too far from 1.5?
Something still needs to be done to language files.

**Comment by jeromerobert** [comment]
Yes, it looks perfect ! I will probably release 1.4.2 tomorrow so you can make your PR.

**Comment by kbengs** [comment]
I couldn't resist the paste interleave..,
this is how it works:
 * user copies or cuts the pages he wants to add interleaved (to clipboard)
 * when pasting, if nothing is selected and user choose:
     * paste interleave odd, pages are added from beginning, first, third,...
     * paste interleave even, pages are added from beginning, second, fourth,...
 * when pasting, if something is selected and user choose:
     * paste interleave odd, first page is added before first selected page, second page is added after first selected page,...
     * paste interleave even, first page is added after first selected page, ...
     * how many pages are selected when pasting does not care, pasting will continue beyond last selected page (if needed)
 * if pages in iconview and pasted pages are not equal number, remaining pages will be added at end/left at end

What do you think about this behavior?

All is in same branch.

**Comment by dreua** [comment]
I'll give it a try and see how it feels asap

**Comment by kbengs** [comment]
I also changed paste after/before so that:
 * When pasting after/before:
    * if nothing is selected, pages are added to to end/to beginning
    * if something is selected, pages are added relative to selection
 * removed (selection) from paste menutext

**Comment by jeromerobert** [comment]
@kbengs It looks good. Do you have any objection to me merging it now?

**Comment by kbengs** [comment]
No I am happy with it, you can merge it. :thumbsup:

**Comment by dreua** [comment]
That great, good work @kbengs  :+1: PDF Arranger is getting really fancy now with drag and drop, undo, redo and now copy & paste :grinning: 
Also the paste odd/even function works really good for me!
