### ISSUE TITLE
Wrong Crop / Rotation on duplicated pages

### ISSUE THREAD

**Issue by dreua** [jeromerobert/pdfarranger#141]
When saving pdfs with duplicated pages and the instances of those have different rotations or crop settings, the rotation / cropping of the first instance of the duplicated page is applied to all the following instances.

Steps to reproduce: 
- Load PDF
- Duplicate a page (either Ctrl+Drag or via menu)
- Change rotation or crop of one of the pages
- Save PDF

Expected results:
Saved PDF looks the same as preview

Actual result:
Saved PDF looks different than preview. All instances of a duplicated page have the same crop / rotation applied.

[Originally reported by Fedora user norbertj, thanks for testing!](https://bodhi.fedoraproject.org/updates/FEDORA-2020-8e8c2b9725)

**Comment by dreua** [comment]
Also affects the "Split Pages" feature

**Comment by jeromerobert** [comment]
I try changing `MediaBox` and `Rotate` on the result of `copy_foreign`  instead of on `current_page`. That does not help :disappointed:.

**Comment by dreua** [comment]
Yeah I tried the same, should have written it here to save you the work :/ Looks like a bug in pikepdf then, doesn't it? I'm also looking into it right now...

**Comment by jeromerobert** [comment]
A bug in PikePDF or in QPDF. `copy_foreign` (and `_add_pages` which was used internally before you introduced `copy_foreign`) should be a deep copy, but it's not. So when we update the `MediaBox` or `Rotate` of a page in update all it's duplicates.

**Comment by dreua** [comment]
Yeah that totally makes sense. They probably never hat that use case before but it's useful especially for the "split pages" function. Are you reporting this upstream or would you want me to do that?

**Comment by dreua** [comment]
The qpdf command can handle it though: `qpdf in.pdf --pages . 1,1,1,1 -- --rotate=180:1,3 out.pdf` (This duplicates the first page of in.pdf 4 times and flips the first and third page.)

**Comment by dreua** [comment]
There is still an issue with cropping, I will have to look into that later.

**Comment by dreua** [comment]
Correction: We are good with the `copy` workaround so the fix can be merged but there is still a bug in pikepdf when setting the mediabox while the rotation is fixed in the latest 1.10.2. I'm going to report that since they probably want to fix that too.

**Comment by dreua** [comment]
Correction 2: Nope, it's on our side. It looks like there is a crop logic in iconview.py and a different one exporter.py / _mediabox. The latter seems to have some bug in combination with pikepdf. I'm out of time now but will try to fix that later today.

**Comment by jeromerobert** [comment]
On let's wait for the mediabox fix, before releasing 1.4.2. I also reproduce it. I'll have a look if I can find time.

**Comment by jeromerobert** [comment]
I no longer reproduce it, so it either depends on the version of pikepdf or on the PDF file.

**Comment by dreua** [comment]
Well I can't reproduce it either today, sorry for the confusion. The `copy.copy(` call and the comment can be removed as soon as it is safe to assume that all users have pikepdf >= 1.20.2 installed.
