### ISSUE TITLE
[UI] Context menu VS Edit menu, Shortcuts

### ISSUE THREAD

**Issue by dreua** [jeromerobert/pdfarranger#142]
I noticed that some of the new features are only in the Edit but not in the Context (right click) menu. Is there some reasoning behind that or should they be added to both (I vote for the latter).

I also would like to have keyboard shortcuts for all actions.

**Comment by jeromerobert** [comment]
Gnome guide lines says "[do not try to assign a keyboard shortcut to everything](https://developer.gnome.org/hig/stable/keyboard-input.html.en#shortcut-keys)". Moreover I prefer to limit the number of shortcuts until we have implemented the [ShortcutsWindow](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/ShortcutsWindow.html) for #87.

I also prefer to keep the right click menu small and only add most common actions. We already have 7 entries. IMHO "Split pages" is to specific to go the that menu. I have no opinion about adding "Edit properties", if you thing it should be added, go on.

**Comment by dreua** [comment]
Ah well I like shortcuts, but i guess there is no point arguing against the gnome guidelines here ;)

In my opinion the "Reverse order" is also quite specific, therefore I was wondering if the "Split Pages" was just forgotten. I know better now, thanks for clarifying! Since "Edit Properties" is not context sensitive it does not really make sense in the context menu imo. (I retract my vote here.)

**Comment by jeromerobert** [comment]
> "Reverse order" is also quite specific

+1

> Since "Edit Properties" is not context sensitive it does not really make sense in the context

+1

**Comment by jeromerobert** [comment]
@dreua I'm back on that issue now that #87 is almost done.

[ShortcutsWindow](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/ShortcutsWindow.html) are manually created so the more you have shortcuts, the more you have to work.

I'll will not use a [GtkPopover](https://developer.gnome.org/gtk3/stable/GtkPopover.html) menu nor a [ShortcutsWindow](https://lazka.github.io/pgi-docs/Gtk-3.0/classes/ShortcutsWindow.html). I prefer to wait for <https://gitlab.gnome.org/GNOME/gtk/issues/903> (Gtk 4).

Plain GtkMenu show shortcuts automatically so maintaining many shortcuts is not a problem anymore. So you can add more shortcuts if you want to.
