### ISSUE TITLE
Thoughts about drag and drop behavior

### ISSUE THREAD

**Issue by kbengs** [jeromerobert/pdfarranger#148]
When dragging a single page the "cursor" is hidden behind the dragged page. Wouldn't it be better if the page would turn into a small icon as when dragging multiple pages? Then the expected drop location would be much more easy to see. (se line: if len(iconview.get_selected_items()) > 1:)

Could the cursor be more clear somehow?

On my computer, kubuntu 19.10, I see no cursor at all. Does anyone know why it is not visible? Do you see a cursor? On Windows 10 I see.

Sometimes when dragging pages and you are not exactly on right place the pages ends up at the end.

**Comment by jeromerobert** [comment]
> When dragging a single page the "cursor" is hidden behind the dragged page.

I don't reproduce that on XFCE so I guess it's desktop dependent.

> Wouldn't it be better if the page would turn into a small icon as when dragging multiple pages

Yes. We could use the `gtk-dnd` stock icon for that. Does it feel better with this ?:

```patch
--- a/pdfarranger/pdfarranger.py
+++ b/pdfarranger/pdfarranger.py
@@ -748,9 +748,10 @@ class PdfArranger(Gtk.Application):
     @staticmethod
     def iv_drag_begin(iconview, context):
         """Sets custom icon on drag begin for multiple items selected"""
-        if len(iconview.get_selected_items()) > 1:
-            iconview.stop_emission('drag_begin')
-            Gtk.drag_set_icon_name(context, "gtk-dnd-multiple", 0, 0)
+        l = len(iconview.get_selected_items())
+        stock_icon = "gtk-dnd-multiple" if l > 1 else "gtk-dnd"
+        iconview.stop_emission('drag_begin')
+        Gtk.drag_set_icon_name(context, stock_icon, 0, 0)
```

> Could the cursor be more clear somehow?

I'm not sure to understand what you mean.

**Comment by kbengs** [comment]
I was thinking about the grey dotted line that can be seen on this picture from windows 10:
![cursor](https://user-images.githubusercontent.com/60842129/75600420-d9559100-5ab7-11ea-81a9-102f6f26aaae.png)

The "cursor" is not completely hidden behind the dragged page, but partly. It is not so easy to see so, to make it more clear I meant if the dotted line could be for example yellow and more thick.

Yes I think it would be better with the icon you suggested.

**Comment by kbengs** [comment]
I have been experimenting with this. Work is in kben/dnd2.

Cursor more easy to see:
* First commit is the suggested gtk-dnd icon when dragging a single page.
* Second commit, the cursor is moved more away (only sideways) from item. Haven't yet find out how to make more distance between item and cursor in Y-direction. 
* Haven't found a way to change the cursor look.

Pages are sometimes (incorrectly) moved to the end:
* Third commit, dnd will not accept drop to location between icons. "Drag cancel animation" does not work when drag to other instance. Don't know if it is possible to make it work.

Cursor invisible in KDE:
* No progress here

What do you think about this, do you have any comments or ideas?

**Comment by kbengs** [comment]
Found a way to change cursor. :) Also KDE cursor visible. More info later.

![Solid cursor](https://user-images.githubusercontent.com/60842129/78896425-221a4580-7a79-11ea-9957-5f4e09759eb3.png)

**Comment by kbengs** [comment]
The right word for cursor is outline. Outline is set in gtk theme css file. At least in KDE the themes Breeze, Ambiance, Radiance and win32 has invisible outline.
Possible outline values:
https://developer.gnome.org/gtk3/stable/chap-css-properties.html
I have made a commit to fix this.

**Comment by jeromerobert** [comment]
Closing thanks to #166. Thank you @kbengs !
