### ISSUE TITLE
Fully automated creation of Windows zip and msi

### ISSUE THREAD

**Issue by jeromerobert** [jeromerobert/pdfarranger#154]
I currently create Windows zip and msi on my gaming PC. It's time consuming, manual, error-prone and unsafe. This should be automated in Github Action. Some references on how it could be done:
* <https://github.com/numworks/setup-msys2>
* <https://github.com/actions/virtual-environments/issues/30>
* <https://github.com/actions/starter-workflows/issues/95>
* <https://github.com/actions/create-release>
* <https://github.com/actions/upload-release-asset>

**Comment by jeromerobert** [comment]
Doing that with Github Action is too difficult for me now. I'll use Docker, Wine, Arch and MSYS2.

**Comment by dreua** [comment]
I'm quit sure I saw someone here on Github using a Docker container in Actions to build stuff, just don't remember where that was unfortunately. But if it is all in a docker container it should be rather easy to automate. [Keeping this issue on my private Todo list.]
