### ISSUE TITLE
TypeError: can't pickle pikepdf._qpdf.Object with pikepdf 1.6

### ISSUE THREAD

**Issue by kbengs** [jeromerobert/pdfarranger#155]
Steps to reproduce:

1. Program started with: 
python3 -m pdfarranger

2. PDF file added.

3. When trying to save this is printed to console:
Traceback (most recent call last):
  File "/tmp/1.4.2_latest/pdfarranger-master/pdfarranger/pdfarranger.py", line 641, in choose_export_pdf_name
    self.save(only_selected, file_out)
  File "/tmp/1.4.2_latest/pdfarranger-master/pdfarranger/pdfarranger.py", line 195, in wrapper
    func(*args, **kwargs)
  File "/tmp/1.4.2_latest/pdfarranger-master/pdfarranger/pdfarranger.py", line 687, in save
    exporter.export(self.pdfqueue, to_export, file_out, m)
  File "/tmp/1.4.2_latest/pdfarranger-master/pdfarranger/exporter.py", line 56, in export
    new_page = copy.copy(pdf_output.copy_foreign(current_page))
  File "/usr/lib/python3.7/copy.py", line 96, in copy
    rv = reductor(4)
TypeError: can't pickle pikepdf._qpdf.Object objects

And file is not saved.

Seems to happen with any PDF file.

Installed pikepdf version:
apt-cache policy python3-pikepdf
python3-pikepdf:
  Installed: 1.6.4+dfsg-1

Problem seems to come after commit c3f2f30

This is tested on Kubuntu 19.10. On Windows 7 it seems to work fine.

**Comment by jeromerobert** [comment]
This is because your pikepdf is too old. We can add a workaround to fix this bug, but I fear that there is no way to make "duplicate" with "crop/rotate" work with a such old pikepdf.

The workaround is to just add a try/except around the `copy.copy`.

@dreua What's your feeling ?

**Comment by dreua** [comment]
Tbh I feel like I'd rather spend time building flatpacks than writing/maintaining workarounds for outdated versions of pikepdf. (And as you said, getting the correct duplicate+crop/rotate behaviour with pikepdf < 1.7.0 is not going to be easy.)
The best solution would be to get a newer pikepdf in your distro. @kbengs maybe you could file a bug against Ubuntu's pdfarranger or pikepdf package? (Or maybe even Debian, I don't know how that stuff works in Debian / Ubuntu land.)
I think the release notes for 1.4.2 should mention that pikepdf >= 1.7.0 is needed and additionally we could add a check for the pikepdf version to notify downstream maintainers and users before they put too much effort in rearranging their pdfs. What would you think about that? 

Most distributions do ship Pikepdf >= 1.7.0. Actually according to repology data, only Debian and it's derivatives as well as nixpkgs ship a version < 1.7.0. (Fedora 29 is EOL)
[![Packaging status](https://repology.org/badge/vertical-allrepos/pikepdf.svg)](https://repology.org/project/pikepdf/versions)
[![Packaging status](https://repology.org/badge/vertical-allrepos/python:pikepdf.svg)](https://repology.org/project/python:pikepdf/versions)

**Comment by kbengs** [comment]
Yes I will update pikepdf anyway. (I would have investigated this more but I knew Jerome maybe was about to release 1.4.2 so I thought it would be good to have info before)
Ubuntu 20.04 will be out in April also and it should ship 1.10.0 according to the list.

**Comment by jeromerobert** [comment]
I will enforce pikepdf >= 1.7.0 in `setup.py` in 1.5.0.
