### ISSUE TITLE
Prefixing .desktop, .appdata.xml and icons with uniqe application ID

### ISSUE THREAD

**Issue by dreua** [jeromerobert/pdfarranger#158]
Hey @jeromerobert, going through the flatpak guidelines it is [recommended but not strictly necessary](https://docs.flatpak.org/en/latest/conventions.html) to rename some files:
- pdfarranger.desktop -> com.github.jeromerobert.pdfarranger.desktop
- pdfarranger.appdata.xml -> com.github.jeromerobert.pdfarranger.**metainfo**.xml (appdata is [still supported](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-location) but while we are at it, I think we can also go the second step and go for metainfo)
- pdfarranger{.png, .svg} -> com.github.jeromerobert.pdfarranger{.png, .svg}
- I wonder if the manpage should also be renamed. It would sound logical to me, but I can't find any information on that. As it is not really important I'd leave it as is.

It is possible and I tried renaming these in the flatpak build process, but now the icon is missing from the about dialogue because pdfarranger can't find it under it's old name any more. It should be possible to fix this with another workaround but maybe it's better to go with the recommendation and rename these in the source, how do you think about this? I can provide a pull-request with these renames and the necessary code changes but before I start working I'd like to hear your opinion.

Related: #37

**Comment by jeromerobert** [comment]
I fullly agree with all that changes. I can see on Debian, that most Gnome and KDE application already follow that naming convention. About the man page, I think it should keep the name of launching script that is just "pdfarranger".

We should also sanitize the `pdfarranger.metainfo.xml` file with [`appstream-util validate`](https://github.com/hughsie/appstream-glib)

**Comment by dreua** [comment]
> We should also sanitize the `pdfarranger.metainfo.xml` file with [`appstream-util validate`](https://github.com/hughsie/appstream-glib)

Looks good to me (0.7.17 is the current release):
```
[da@David-UB data (master)]$ flatpak run org.freedesktop.appstream-glib validate pdfarranger.appdata.xml
pdfarranger.appdata.xml: OK
[da@David-UB data (master)]$ appstream-util validate pdfarranger.appdata.xml 
pdfarranger.appdata.xml: OK
[da@David-UB data (master)]$ appstream-util --version
Version:	0.7.17
```
(I also ran it against the renamed file with the same results.)

**Comment by dreua** [comment]
validate-strict on the other hand is not entirely happy: 

```
[da@David-UB pdfarranger (appid-prefix *)]$ appstream-util validate-strict data/com.github.jeromerobert.pdfarranger.metainfo.xml 
data/com.github.jeromerobert.pdfarranger.metainfo.xml: FAILED:
• aspect-ratio-invalid  : <screenshot> aspect ratio not 16:9 [http://screenshots.debian.net/screenshots/000/017/031/large.png]
• style-invalid         : <p> requires sentence case [pdfarranger is a small application, which helps the user to merge or split pdf documents and rotate, crop and rearrange their pages using an interactive and intuitive graphical interface. It is a frontend for pikepdf.]
• translations-required  : <name> has no translations
• translations-required  : <summary> has no translations
• translations-required  : <description> has no translations
Validation of files failed
```

The style-invalid issue raises the question how pdfarranger is correctly spelled. The desktop file lists PDF Arranger but on all other occurrences it seems to be pdfarranger.
