### ISSUE TITLE
MSI Installer doesn't trigger UAC

### ISSUE THREAD

**Issue by licaon-kter** [jeromerobert/pdfarranger#159]
...since 1.4.0, so it will fail to install since it can't write files in `Program Files` as its missing Admin right.

W10 1909

**Comment by dreua** [comment]
Same here (tested 1.4.1). 

Workaround: Install it somewhere in the users's home directory so write access is not an issue. 

Maybe we can set this as default as most users are probably installing pdf arranger only for themselves. Additionally I think I have seen some programs installing somewhere into appdata by default.

**Comment by licaon-kter** [comment]
Or install 1.3.1 then overwrite the files with those from latest .zip.

**Comment by jeromerobert** [comment]
@licaon-kter Do you mean that 1.3.1 trigger the UAC ?

That would be strange because from this:
* https://github.com/anthony-tuininga/cx_Freeze/blob/master/cx_Freeze/windist.py#L417
* https://github.com/orestis/python/blob/master/Tools/msi/msilib.py#L293

cx_freeze does not support UAC.

I like @dreua proposal.

**Comment by dreua** [comment]
Just tried it: 1.3.1 triggers UAC during installation

**Comment by jeromerobert** [comment]
Thanks. Now I just have to find if it happen because I switched from cx_freeze 5 to 6, or because I switched from the MSYS2 package to the pip package of cx_freeze.

**Comment by jeromerobert** [comment]
Single user installation is the default behavior in cx_freeze 6.1: https://github.com/anthony-tuininga/cx_Freeze/commit/edd7146ef8b94f0994df46395cadedf60f7af967. I will just change the default installation folder to `%LocalAppData%\pdfarranger`, so UAC won't be needed anymore. Multi-user installation will still be supported using `msiexec /i pdfarranger.msi TARGETDIR="%ProgramFiles%"` from an administrator `cmd`. I can't find a way to set a different default target directory for single user and multi-user context.
