### ISSUE TITLE
App has doubled in size

### ISSUE THREAD

**Issue by licaon-kter** [jeromerobert/pdfarranger#160]
...is that expected?

**Comment by jeromerobert** [comment]
Oops, no it's not. I forgot to get https://github.com/jeromerobert/cx_Freeze/commit/0da6b32e0ac909c8fbcea8de2529ac136fff1ce6 before doing the package. This is also related to #154.

**Comment by jeromerobert** [comment]
```
$ du -h dist/*
32M	dist/pdfarranger-1.5.0-mingw.msi
31M	dist/pdfarranger-1.5.0-mingw.zip
```
