### ISSUE TITLE
pdfarranger not starts

### ISSUE THREAD

**Issue by stolzpet** [jeromerobert/pdfarranger#167]
Hello,

I compiled pdfarranger all seems to work fine:
./setup.py build
running build
running build_py
running build_i18n
intltool-update -p -g pdfarranger
running build_icons

But pdfarranger not starts:
python3 -m pdfarranger
Traceback (most recent call last):
  File "/home/stolz/pdfarranger-1.4.2/pdfarranger/pdfarranger.py", line 356, in do_activate
    self.uiXML.connect_signals(self)
ValueError: Pointer arguments are restricted to integers, capsules, and None. See: https://bugzilla.gnome.org/show_bug.cgi?id=683599

How to fix this error?

**Comment by stolzpet** [comment]
python3-gobject-devel solved problem

**Comment by jeromerobert** [comment]
For the record, duplicate of #88
