### ISSUE TITLE
Zoom Accelerators: +/- on main Keyboard works but not on Numpad

### ISSUE THREAD

**Issue by dreua** [jeromerobert/pdfarranger#169]
I think it would be an improvement, if the +/- keys on the numpad worked as zoom accelerators as well. This would match the behavior of Evince.

**Comment by jeromerobert** [comment]
I won't have access to a numpad for a week or two, so I keep that commit on hold unless someone test it.

**Comment by dreua** [comment]
That works and can go directly to master imo, thanks!
