### ISSUE TITLE
pdfarranger 1.5.0 installation error on windows 10

### ISSUE THREAD

**Issue by antonsurv** [jeromerobert/pdfarranger#176]
pdfarranger.exe- entry point not found
the procedure entry point g_log_structured_standard could not be located in the dynamic link library
C:\Users\..\..appdata\local\programs\pdfarranger\libpango-1.0-0.dll
![python error](https://user-images.githubusercontent.com/51750998/79242299-57220000-7e9e-11ea-9435-820ab7223de0.PNG)

I downgraded to 1.4.2

**Comment by jeromerobert** [comment]
Is it with the .zip or the .msi ?

**Comment by antonsurv** [comment]
msi Sir

**Comment by jeromerobert** [comment]
> The size v.1.4.2 is 136 MB, but v.1.5.0 is 70 MB.

See #160

> Is there something I miss about dependencies on windows 10 installation?

I don't think so. As I cannot reproduce the issue I would say you have some other version of gtk or mingw in your PATH and they conflict with pdfarranger (something similar to #122). 1.4.2 have older version of python, gtk, pikepdf and may be it's enough to hide that conflict.

Could try to run pdfarranger.exe from command line after cleaning `PATH`. Something like:

```
set PATH=C:\Windows\system32;C:\Windows
cd C:\Users\Anton\AppData\Local\Programs\pdfarranger
pdfarranger.exe
```

You can try with the .zip file so you don't have to uninstall the 1.4.2 version.

**Comment by antonsurv** [comment]
> set PATH=C:\Windows\system32;C:\Windows
> cd C:\Users\Anton\AppData\Local\Programs\pdfarranger
> pdfarranger.exe

the program had no issue with cmd command. It's normally open.



> You can try with the .zip file so you don't have to uninstall the 1.4.2 version.

zip version also good.

I think the problem is when I open in icon on my start menu. 

Thank you so much. I love pdfarranger. The best pdf arranger tools.

**Comment by jeromerobert** [comment]
As this is the second time such issue is reported and I don't know why it happen, I'll let that bug open. 

From https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order the first folder which is searched for a DLL is *the directory from which the application loaded*. I understand this as *the folder which contains `pdfarranger.exe`*.

There may be a difference between running from the MSI `.lnk` file (start folder) and from command line. In the first case the current folder may be anything and in the second case it's more likely the folder containing `pdfarranger.exe`. But it should not change the way DLL are searched.

```
cd C:\Users\Anton
C:\Users\Anton\AppData\Local\Programs\pdfarranger\pdfarranger.exe
```

would confirm if the current folder does or doesn't matter.

I'll try to reproduce that bug by adding some buggy DLLs to my PATH or system folder.

**Comment by jeromerobert** [comment]
I tried to add a buggy libpython to my PATH but I was enable to reproduce that issue.

**Comment by antonsurv** [comment]
You're right Sir, I have tried installing msi on the fresh Windows 10 VM, there's no issue with msi installer. I guess some malware mess up my start menu windows 10. You can close this issue. Thank you.
