### ISSUE TITLE
Option to duplicate page(s)

### ISSUE THREAD

**Issue by jeromerobert** [jeromerobert/pdfarranger#18]
*Add a right-click option to duplicate selected page(s) ([sf](https://sourceforge.net/p/pdfshuffler/bugs/47/), [savannah](https://savannah.nongnu.org/bugs/index.php?54823))* (quoting  @darkdragon-001)

**Comment by dreua** [comment]
Workaround: It is already possible to duplicate pages by holding Ctrl while Drag&Dropping an item or a selection. (With the bug that one page of the selection might become deselected and is not duplicated, but let's postpone this until DnD in general is fixed.)
I am not against such a right-click option, though.

**Comment by jeromerobert** [comment]
Should be done **after** #59.
