### ISSUE TITLE
List pdfarranger on LGTM for automated code review and security analysis

### ISSUE THREAD

**Issue by digitalethics** [jeromerobert/pdfarranger#180]
Could you list pdfarranger on [LGTM](https://lgtm.com/) for automated code review and security analysis? As I see it, this would have two major benefits. End users as well as distribution maintainers will be able to quickly assess the code quality in form of an automated code quality batch (ideally rated A+) displayed on GitHub, and secondly, you may prevent bugs from appearing in your project by already catching them in the review process.

**Comment by jeromerobert** [comment]
@kbengs Could you have a look to the 2 warnings about `Except block handles 'BaseException'` raised by LGTM ? <https://lgtm.com/projects/g/jeromerobert/pdfarranger/alerts/?mode=list>

**Comment by kbengs** [comment]
Yep, I did some testing now and it seems that we can only have ValueError or FileNotFoundError here. But I will look more into it later and make a PR.
