### ISSUE TITLE
Save as button stays always grayed out

### ISSUE THREAD

**Issue by dreua** [jeromerobert/pdfarranger#181]
Update works without problems. Just the _Save as_ button stays always grayed out. The option in the main menu works though.

_Originally posted by @darkdragon-001 in https://github.com/jeromerobert/pdfarranger/issues/37#issuecomment-614221242_

Confirmed on flatpak and pip install.

Additionally the Save button is never grayed out.

**Comment by dreua** [comment]
@jeromerobert do you have plans for 1.5.1 eta wise? I got [another report from Fedora user kbengs](https://bodhi.fedoraproject.org/updates/FEDORA-2020-516b2779e7) and I'm wondering if I should patch this at least for the Fedora update. New release would be easier for me tbh. Maybe we can also squeeze #178 in. (I should be able to provide a PR for that soon.)

**Comment by jeromerobert** [comment]
I would like to release 1.5.1 not later than next monday because I'll be more busy after. #182 and #178 are not regressions so it's not that bad to release without having fixed them. But if they are, it's nice.
