### ISSUE TITLE
Drag and drop doesn't work (Windows 10)

### ISSUE THREAD

**Issue by StefRe** [jeromerobert/pdfarranger#182]
Drag and drop doesn't work (neither between file explorer and pdfarrange, nor between two instances of pdfarrange) - just nothing happens:
![drag_and_drop](https://user-images.githubusercontent.com/19879328/79476179-ed723500-8008-11ea-96d7-988b7a9e6a87.gif)
(the file is a valid pdf and can be imported by the menu as you can see in the second half of the video)

Copy and paste doen't work either (not sure if this is supposed to work from file explorer though):
![copy_and_paste](https://user-images.githubusercontent.com/19879328/79476259-0aa70380-8009-11ea-8598-b577de5e94fa.gif)
 (the file was indeed copied to the clipboard as you can see in the second half of the video where it get's pasted into file explorer).

pdfarranger version 1.5.0, Windows 10.

(oh, I forgot to say: great program with nice user interface! Keep it up!)

**Comment by kbengs** [comment]
The first case (drag file from explorer to pdfarranger) I have looked at and got it working. I can make a PR for it later.

**Comment by jeromerobert** [comment]
It was already not working in 1.4.2. It has probably never worked.

**Comment by jeromerobert** [comment]
Fixed by c1662a3, thank you kbengs !

**Comment by kbengs** [comment]
@jeromerobert, drag pages between two instances was also mentioned here. And that is still unsolved. :) (And add pdf file by right clicking on a pdf file in Explorer and paste to Pdfarranger..)

**Comment by jeromerobert** [comment]
oops

**Comment by dreua** [comment]
> And add pdf file by right clicking on a pdf file in Explorer and paste to Pdfarranger..

You mean by copy and paste from file explorer? That is not even supported on Linux. Would be cool though.

**Comment by StefRe** [comment]
Thank you @kbengs! Drag and drop from file explorer was my main concern. Dragging between two instances of `pdfarranger` I only tried because I saw the three possible IDs [here](https://github.com/jeromerobert/pdfarranger/blob/c1662a39db2a9b70ab88035df4af6e05de2ea9f6/pdfarranger/pdfarranger.py#L216). And trying to insert a file from clipboard that was copied to clipboard in the file explorer was just out of curiosity.

**Comment by kbengs** [comment]
If this line:
"os.environ['GDK_WIN32_USE_EXPERIMENTAL_OLE2_DND'] = 'any text'"
is added to pdfarranger.py, drag to other instance works in Windows. Problem is that drag_data_delete is not emitted, so pages are not deleted on source instance. Also copy-drag
(crtl + drag) does not work in same instance. Other than that I see no problem with it.

If also "else: return True" is added to end of iv_dnd_motion function, drag_data_delete is emitted on some occasions. But it feels almost random when it does and also cursor is invisible, so it seems like its not possible to make it work this way.

I guess it could be made to work if we could emit a signal on received instance that would trigger drag_data_delete on source instance.
I tried to search for a way to do that but couldn't find a good way. Do someone have any suggestions how that could be done?

**Comment by jeromerobert** [comment]
Unless I've missed something again, this time kbengs has really got it covered. Closing.
