### ISSUE TITLE
Some file names could do with a bit of simplification

### ISSUE THREAD

**Issue by brobr** [jeromerobert/pdfarranger#189]
Hi, Thanks a lot for pdfarranger. I just discovered it after years of pdfshuffler use and fearing the days that python2 will be obsolete and that that great 'little' program would go with it. Well, not. Fabulous. (I plan to submit a buildscript to slackbuilds.org for your program as an alternative/replacement for pdfshuffler.)

Compiling pdfarranger with a first build script showed that some filenames (for icons etc.) seem unneccessary long, having `com.github.jeromerobert` as a start. 

Removing that extension, thus with the following in the buildscript,  does not affect function on my box:
>mv $PKG/usr/share/applications/com.github.jeromerobert.pdfarranger.desktop \
$PKG/usr/share/applications/pdfarranger.desktop
>
>mv $PKG/usr/share/metainfo/com.github.jeromerobert.pdfarranger.metainfo.xml \
$PKG/usr/share/metainfo/pdfarranger.metainfo.xml
>
>find $PKG/usr/share/icons/hicolor/ -iname 'com.github.jeromerobert.pdfarranger.png' -exec rename com.github.jeromerobert.pdfarranger.png pdfarranger.png '{}' ';'

Maybe this is something that could be repaired in the source?

**Comment by jeromerobert** [comment]
I basically agree but we are not deciding of FreeDesktop, Gnome and FlatHub conventions. See:

* #158
* https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html
* https://docs.flatpak.org/en/latest/conventions.html
* your `/usr/share/metainfo/` folder

So I fear that those file name will remain that long.

**Comment by dreua** [comment]
Jerome's comment says it all. I personally think it's no big deal since you normally don't work with these files.


> I plan to submit a buildscript to slackbuilds.org for your program as an alternative/replacement for pdfshuffler.

I think that's great! I'd like you to have a look at our [wiki page on binary packages](https://github.com/jeromerobert/pdfarranger/wiki/Binary-packages) for two reasons:

 1. You can add a link to your package/buildscript there if it is done. (Or notify me if you want me to do that.)
 1. I don't know slack but maybe the other build recipes there can help you create one for slack. I maintain builds for Fedora, openSUSE and Flatpack, feel free to ping me if I can help with anything.

**Comment by brobr** [comment]
Well, two points; it won't be a binary distribution but just build scripts with sufficient info so that the application can be compiled on a user's machine and then installed using Slackware's pkgtools.

Second, thanks for the links. But, sorry, despite what the flatpackers want,  I do not see a strong argument for using the names as they do. Their overuse of application ID, is - from a UI point of view (which should be decisive in these kind of issues) -  horrible and off-putting; when searching for the icon, say on XFCE:
![name-Screenshot_2020-04-21_12-23-01](https://user-images.githubusercontent.com/3693709/79861770-cd59c180-83cc-11ea-828f-cd3c483abfa1.png)

https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html says:
>local icons are loaded from a file in the filesystem. They should specify a full file path. This icon type may have width and height properties. 

So not much info about the icon's name there. But the application id seems only present in the xml-file for the application:
>\<?xml version="1.0" encoding="UTF-8"?>
​\<component>
   ​\<id>com.example.foobar\</id>
   \<name>Foo Bar\</name>
..

On https://docs.flatpak.org/en/latest/conventions.html they provide a beautiful example of how to screw up UI appearance
>/app/share/icons/hicolor/128x128/apps/org.gnome.Dictionary.png

It's all about preventing names overwriting each other; well don't use such common names as 'Dictionary' should be the advice, and if so, only then you would need to overload it with that id. 

So I'll keep those lines in my build script, they do the job. And if ever gnome releases its own pdfarranger, well so be it; won't use their version if this one is still alive and kicking.

**Comment by dreua** [comment]
> Well, two points; it won't be a binary distribution but just build scripts with sufficient info so that the application can be compiled on a user's machine and then installed using Slackware's pkgtools.

I understand the difference and I personally think we can add that to the wiki page anyway.

For the second point: I did not want to push you in any direction, I merely tried to be helpful. (Maybe my wording was not great, I'm not a native speaker.)

**Comment by brobr** [comment]
No problem,  here, those lines can always be commented out for anyone who wants to stick to the rules (I am not so inclined when rules seem to take over and go beyond their purpose; a consistent UI seems more important). 

BTW due to library incompatibilities (qpdf) in the released Slackware distribution (followed by SlackBuilds.org) submission of a Slackbuild for pdfarranger will have to wait until the next release (which is already in development as 'current'). At the moment the scripts are available here; https://github.com/brobr/SLACKBUILDtrees
