### ISSUE TITLE
Cannot launch from context menu because of Qt en_SE locale

### ISSUE THREAD

**Issue by mankoff** [jeromerobert/pdfarranger#193]
Using this PDF: https://www.the-cryosphere.net/14/1347/2020/tc-14-1347-2020.pdf I can open from the command line, but not by right-clicking on the PDF and selecting "Open With"

System info: Kubuntu 20.04

**Comment by jeromerobert** [comment]
You should be able to get an error message by reading the end of your `$HOME/.xsession-errors` file after reproducing that error.

**Comment by dreua** [comment]
Alternatively monitor `journalctl --follow` while doing your "Open with", there will be some unrelated output but it's usually possible to find the relevant stuff. Ctrl+C stops the process in case that's not obvious. 

How did you install pdfarranger?

**Comment by mankoff** [comment]
Installed with `sudo apt install pdfarranger`. 

Here is the output from `~/.xsession-errors`:

```

Cannot initialize model with data QJsonObject() . missing: QJsonValue(string, "urls")
kdeinit5: Got EXEC_NEW '/usr/lib/x86_64-linux-gnu/qt5/plugins/kf5/kio/tags.so' from launcher.
kdeinit5: preparing to launch '/usr/lib/x86_64-linux-gnu/qt5/plugins/kf5/kio/tags.so'
kf5.kio.kio_tags: tag fetch failed: "Failed to open the database"
kf5.kio.kio_tags: "tags:/" list() invalid url
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 46762, resource id: 35663794, major code: 18 (ChangeProperty), minor code: 0
Traceback (most recent call last):
  File "/usr/bin/pdfarranger", line 11, in <module>
    load_entry_point('pdfarranger==1.4.2', 'console_scripts', 'pdfarranger')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/pdfarranger/pdfarranger.py", line 49, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.8/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 47038, resource id: 35663795, major code: 18 (ChangeProperty), minor code: 0



```

**Comment by dreua** [comment]
I've seen that issue with the flatpak but since this is not a flatpak probably unrelated. Could be a damaged or missing locale or a locale variable set to something that is not installed. Did you have any other issues or special configuration related to locale (e.g. modifying it in .bashrc or something)? 

I understand that it works from the command line but not from the open with menu. What about the application menu?

Can you post the output of `locale` from a terminal where pdfarranger works? Ideally also from a environment where pdfarranger doesn't work if you can pull this off, I might be able to give step by step instructions for that later.

**Comment by mankoff** [comment]
`local` output from my terminal is:

```bash
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME=C.UTF-8
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```

**Comment by mankoff** [comment]
This all worked last week using 18.04 and pdfshuffler. This is a clean 20.04 with region set to `en_US` but Time set to `en_SE` in the Formats section.

**Comment by dreua** [comment]
I could reproduce the problem only with Time set to en_SE but for me it affects running from command line too. 
The issue is not exactly pdfarranger but a missing locale or an invalid locale setting. I'll create another issue to discuss if we should catch this error and fall back to a working default in pdfarranger.

Can you confirm that you have the same results when running these commands:
```
$ locale -a | grep en_SE
(No output i.e. not available.)
```
```
$ export LC_TIME=en_SE.UTF-8
bash: warning: setlocale: LC_TIME: cannot change locale (en_SE.UTF-8)
```
In my case I can easily reproduce the error with the interactive python shell:
```
$ python3
Python 3.8.2 (default, Mar 13 2020, 10:14:16) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.setlocale(locale.LC_ALL, "")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by mankoff** [comment]
I confirm same as above. Is there some environment variable I should be setting somewhere? I'm happy to solve this outside of pdfarranger. I use en_SE because I like my dates ISO-format: YYYY-MM-DD and that is the only way to get that display (that I know of) in KDE.

**Comment by dreua** [comment]
Actually I think this is a KDE bug - it should be possible to ship with an en_SE locale that works for all apps including non-KDE/Qt apps.

**Comment by jeromerobert** [comment]
https://unix.stackexchange.com/questions/410844/how-to-hack-and-modify-a-predefined-date-time-format-of-kde-5-that-comes-with-de

`en_SE` does not exists in the glibc but but only in Qt. I don't think we can do anything in pdfarranger. If you want to keep `LC_TIME=en_SE` session wide, you should add a `LC_TIME=""` to all non-KDE application launcher. Or you may keep a standard `LC_TIME` session wide and set it to `en_SE` only in launcher of Qt applications where you do care about the date format. I admit this deadly cubersome.

If you agree I will close this bug and keep #196 open.

**Comment by mankoff** [comment]
Thanks for digging into this. Yes, this seems like it isn't really a `pdfarranger` bug. Closing is fine.
