### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file...

### ISSUE THREAD

**Issue by kbengs** [jeromerobert/pdfarranger#194]
This error is in Windows. Steps to reproduce:
* install pdfarranger-1.5.1-mingw.msi
* download source code and move pdfarranger.py to same folder as pdfarranger.pyc
* add line: sys.stderr = open('C:\Temp\stderr.log', 'w') to pdfarranger.py
* start pdfarranger
* drag ok pdf file to app
* drag broken pdf file to app
* close app

After this C.\Temp:\stderr.log looks like this:
PDF document is damaged: C:\Temp\Broken pdf.pdf
Traceback (most recent call last):
  File "C:\Users\kbengs\AppData\Local\Programs\pdfarranger\lib\pdfarranger\pdfarranger.py", line 650, in close_application
    shutil.rmtree(self.tmp_dir)
  File "Z:\mingw64\lib\python3.8\shutil.py", line 737, in rmtree
  File "Z:\mingw64\lib\python3.8\shutil.py", line 615, in _rmtree_unsafe
  File "Z:\mingw64\lib\python3.8\shutil.py", line 613, in _rmtree_unsafe
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\kbengs\\AppData\\Local\\Temp\\tmp57728wkspdfarranger\\tmp860j06g_'

This error also happens in MSYS2 environment when started with /mingw64/bin/python3 - m pdfarranger

**Comment by jeromerobert** [comment]
* Unexpectedly, the temporary file which cannot be deleted is not the one of the broken PDF file but the one of good PDF file
* The bug vanish if I call `gc.collect()` before running `shutil.rmtree`
* The bug also vanish if I remove the modal dialog box which show the *PDF document is damaged* message (added in a34b315 by @dreua )

Until now I relied on the garbage collector to free the Poppler document and it worked. But it seems not safe as just adding a modal dialog box change the behavior. So unless someone has better idea I'll add a `gc.collect()` in `close_application`.
