### ISSUE TITLE
Error with save since update to ubuntu 20.04

### ISSUE THREAD

**Issue by AlainEspe** [jeromerobert/pdfarranger#195]
When I save, I have the code error:
don't know how to __str__ this object
in console:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pdfarranger/pdfarranger.py", line 680, in choose_export_pdf_name
    self.save(only_selected, file_out)
  File "/usr/lib/python3/dist-packages/pdfarranger/pdfarranger.py", line 196, in wrapper
    func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pdfarranger/pdfarranger.py", line 725, in save
    m = metadata.merge(self.metadata, self.pdfqueue)
  File "/usr/lib/python3/dist-packages/pdfarranger/metadata.py", line 63, in merge
    meta.load_from_docinfo(doc.docinfo)
  File "/usr/lib/python3/dist-packages/pikepdf/models/metadata.py", line 314, in load_from_docinfo
    msg = (
NotImplementedError: don't know how to __str__ this object

**Comment by dreua** [comment]
Is this happening only with one/some specific files or with all PDFs you tried? (Take a [wikipedia export](https://en.wikipedia.org/w/index.php?title=Special:ElectronPdf&page=PDF&action=show-download-screen) if you need samples.)

If it is only one files or files from one specific source we need such a file as an example to reproduce.

**Comment by dreua** [comment]
Additionally it never hurts to state the version(s) of the faulty software. `sudo apt list "*pdfarranger*" "*pikepdf*"` should return those.

**Comment by AlainEspe** [comment]
`pdfarranger/focal,focal,now 1.5.1-0~focal0 all  [installé]
pikepdf-doc/focal,focal 1.10.3+dfsg-1 all
python3-pikepdf/focal,now 1.10.3+dfsg-1 amd64  [installé]'
Not whith all pdf. For example:
[Algo_Extrem.pdf](https://github.com/jeromerobert/pdfarranger/files/4553811/Algo_Extrem.pdf)

**Comment by dreua** [comment]
Reproduced with pdfarranger 1.4.2 on Fedora 31

Reproduced with pdfarranger 1.5.1 on Fedora 31 (Flatpak):
```
$ flatpak run com.github.jeromerobert.pdfarranger
Gtk-Message: 21:08:28.139: Failed to load module "pk-gtk-module"
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/pdfarranger/pdfarranger.py", line 680, in choose_export_pdf_name
    self.save(only_selected, file_out)
  File "/app/lib/python3.7/site-packages/pdfarranger/pdfarranger.py", line 196, in wrapper
    func(*args, **kwargs)
  File "/app/lib/python3.7/site-packages/pdfarranger/pdfarranger.py", line 725, in save
    m = metadata.merge(self.metadata, self.pdfqueue)
  File "/app/lib/python3.7/site-packages/pdfarranger/metadata.py", line 63, in merge
    meta.load_from_docinfo(doc.docinfo)
  File "/app/lib/python3.7/site-packages/pikepdf/models/metadata.py", line 317, in load_from_docinfo
    ).format(extra, docinfo.get(extra))
NotImplementedError: don't know how to __str__ this object
```

I think this is unrelated to your ubuntu update.

**Comment by dreua** [comment]
It looks like an error in pikepdf to me. Introduced in v1.9.0 so it came with your Ubuntu update. Any pikepdf <= 1.8.3 should work as a workaround. I'll report that to pikepdf.

**Comment by dreua** [comment]
Pikepdf 1.11.2 has been released with a fix for this issue and I [rebuilt the Flatpak](https://github.com/flathub/com.github.jeromerobert.pdfarranger/pull/3) with this pikepdf update. Now the PDF can be exported without loosing all metadata, only then one value that pikepdf can't read is discarded and the Warning message is shown in a dialog. 

![metadata_warning](https://user-images.githubusercontent.com/15114715/81092616-27946f80-8f01-11ea-9b32-552510fe08f2.png)

This warning dialog has a UX issue: It can be hidden by clicking on the file chooser behind it and then both the file chooser and the Warning can only be closed by pressing Escape.

**Comment by jeromerobert** [comment]
With 6a53703 there should not be any dialog for that, just a stack in the console. I guess that your remark about the warning dialog is for 1.5.2, right ?

**Comment by dreua** [comment]
Assuming you meant 1.5.1, yes that is what I tested. But I don't think your workaround applies here anyway since the NotImplementedException is not thrown with the new Pikepdf. Iirc we had some method that collects everything written to stdout/stderr during export and displays it in the warning dialog even if there is no error thrown.

Not a strong opinion but I like to have this information in Gui, I'd just fix the UX by one of those:
 - Close the file chooser before the message box is shown
 - Make the warning dialog it stay on top of the file chooser at all times
 - Let both dialogs properly be closed without needing to find the Esc-key workaround

(I'd say whatever is easiest.)

Should I create a new issue for that?

**Comment by jeromerobert** [comment]
> Assuming you meant 1.5.1

Yes ;-)

> Close the file chooser before the message box is shown

More likely the easiest. Does 3c83535 looks good to you ? IMHO the `while` loop was just a reminiscence of the past.

**Comment by dreua** [comment]
That's perfect imo. Tested and works like it should, the while True: ... break loop didn't make any sense, thanks for cleaning that up and fixing!

**Comment by dreua** [comment]
Don't forget to push it to master!
