### ISSUE TITLE
Select even and odd pages

### ISSUE THREAD

**Issue by felix-wo** [jeromerobert/pdfarranger#197]
It would be very handy to be able to select all even or all odd pages of a PDF. The old (and buggy) "PDF Mod" had it. A common use case is arranging the pages of a scan from a book, where it is often more convenient or more accurate to scan every even page upside down.

Thank you for your work!

**Comment by kbengs** [comment]
I would also suggest "select all". This would be useful when you want to remove all pages: right click -> select all -> delete.

**Comment by dreua** [comment]
> I would also suggest "select all".

Ctrl + A already works and I use it often but we don't have a menu item for it.

What I miss is the possibility to remove single pages from selection by Ctrl+Clicking them. (At the moment this deselects everything but the clicked page. Adding by Ctrl+Click is already implemented.)

**Comment by kbengs** [comment]
I didn't know about Ctrl + A. :+1: A help page with for example shortcuts would also be nice. :-)

**Comment by felix-wo** [comment]
I agree with all these comments. "PDF Mod", which is obviously the role model for "PDF arranger" (and "PDF Shuffler" in the first place) had all these features in the menus. It was (and is) a really useful tool, but it has heavy bugs, unfortunately.

**Comment by kbengs** [comment]
@jeromerobert what do you think about if we would add a select sub menu that would have:
Select even
Select odd
Select all
Deselect all
Invert selection

I could work on this.

**Comment by jeromerobert** [comment]
@kbengs That sounds good

**Comment by jeromerobert** [comment]
Done by kbengs in 65c564d
