### ISSUE TITLE
opensuse: running pdfarranger fails : missing dependency : Namespace Poppler not available

### ISSUE THREAD

**Issue by rich-coe** [jeromerobert/pdfarranger#200]
I'm trying to run pdfarranger on opensuse.
I successfully installed pdfarranger with pip3.
When I try to run it:

    Traceback (most recent call last):
      File "/usr/local/bin/pdfarranger", line 5, in <module>
        from pdfarranger.pdfarranger import main
      File "/usr/local/lib/python3.8/site-packages/pdfarranger/pdfarranger.py", line 93, in <module>
        gi.require_version('Poppler', '0.18')
      File "/usr/lib64/python3.8/site-packages/gi/__init__.py", line 129, in require_version
        raise ValueError('Namespace %s not available' % namespace)
    ValueError: Namespace Poppler not available

The python3 poppler interface was already installed: python3-poppler-qt5
What pdfarranger is apparently looking for is another python3 interface similar to GTK gobjects.
/usr/lib64/python3.8/site-packages/gi/overrides/Gtk.py

I have not found any packages or suppliers that makes gobject style poppler interface for python.

Further investigation shows https://gitlab.gnome.org/GNOME/pygobject may be the origin of this dependency.  

There doesn't seem to be any support for this python poppler package except for debian.

**Comment by merwok** [comment]
You need a package that provides «gobject introspection», which is IIUC generated bindings for a lib for all languages that GTK supports.  On debian it’s `gir1.2-poppler-0.18`.

**Comment by dreua** [comment]
Try installing typelib-1_0-Poppler-0_18

I have an experimental spec file for openSUSE Tumbleweed here: https://github.com/dreua/pdfarranger-rpmspec/blob/opensuse/pdfarranger.spec

That is the source for this copr build: https://copr.fedorainfracloud.org/coprs/dreua/pdfarranger-openSUSE/

**Comment by dreua** [comment]
And since this is distro specific, please add openSUSE to the issue title ☺️

**Comment by rich-coe** [comment]
woot.  typelib-1_0-Poppler-0_18  creates /usr/lib64/girepository-1.0/Poppler-0.18.typelib which is what is needed.  
thanks.

**Comment by dreua** [comment]
You're welcome! 

Out of curiosity: Have you seen our [Binary packages page](https://github.com/jeromerobert/pdfarranger/wiki/Binary-packages)? It contains links to another openSUSE issue and those I already posted above. You could possibly have found your solution there but I assume the page lacks some visibility or it is not obvious that one might find such information on a "Binary packages" page.

**Comment by rich-coe** [comment]
I did not see the Binary packages.  I see I went completely past 'Binary distribution' on the README and went to pip3 install.  I did google all forms and combinations of 'opensuse' 'pdfappender' 'ValueError: Namespace Poppler not available'.  All I kept finding was the Debian package failure for 'mat'.

**Comment by dreua** [comment]
Alright, thank you for that information! If you were actually searching for pdfa*ppend*er, try pdfa*rrang*er next time :wink:

**Comment by rich-coe** [comment]
argh.  all the letters and grammar were correct and in the right place.
