### ISSUE TITLE
Poll for new application icon (please contribute)

### ISSUE THREAD

**Issue by smonsays** [jeromerobert/pdfarranger#205]
I am an avid user of pdfarranger and was wondering if the project would be interested in updating its application icon?
I have made a draft as a suggestion but am happy to modify it further (it is an svg file, but I cannot directly embed that here):

![pdfarranger-icon](https://user-images.githubusercontent.com/8426567/82139806-1bba7e80-981a-11ea-864a-435678598543.png)

**Comment by jeromerobert** [comment]
I don't really care. Let's the community speak out.

**Comment by kbengs** [comment]
With the one we have now it's hard to imagine what the small icon is showing. So I think it could be better. Maybe this. Maybe the word PDF could be visible in some way?

**Comment by smonsays** [comment]
> Maybe this. Maybe the word PDF could be visible in some way?

I like that suggestion, maybe something like this?

![rect954](https://user-images.githubusercontent.com/8426567/82145523-a2328880-9839-11ea-82ca-f23d88504f8e.png)

**Comment by bertob** [comment]
I was also playing with an icon idea and found this issue :)

Here's what I have atm:

![image](https://user-images.githubusercontent.com/1908896/82150892-f0f01a80-9859-11ea-972f-b321f7dd8017.png)

I don't love the metaphor, but with PDFs/documents that's always hard. Any ideas for physical objects/metaphors I could try instead would be appreciated.

**Comment by bertob** [comment]
Another variant

**Comment by mimi89999** [comment]
@bertob I think that the colors of the second variant don't match GNOME Adwaita colors to well.

**Comment by jeromerobert** [comment]
So far my preferred one is the last alternative of smonsays because:
* The two arrow in circle of bertob is beautiful but let me think more about reloading something than arranging.
* The third alternative of smonsays fit more in a square than the second one so it's better for tiny icons

**Comment by merwok** [comment]
Hi, long-time user of PDF Shuffler then PDF Arranger :slightly_smiling_face: 

I like the current icon, otherwise the third version by smonsays.
Suggestion: add some straight arrows between the documents to suggest «arrangement»

**Comment by bertob** [comment]
> I think that the colors of the second variant don't match GNOME Adwaita colors to well

Third party apps are encouraged to use off-palette colors for some things, in order to have a more recognizable identity. That said, those colors weren't chosen for any particular reason, I'd be happy to try something different.

**Comment by smonsays** [comment]
I reiterated on my suggestion to integrate it a bit better with the Adwaita design language:

![g2813](https://user-images.githubusercontent.com/8426567/82193021-4ffa7180-98e4-11ea-8aee-4e04f77e7c5c.png)

**Comment by dreua** [comment]
@smonsays I'd like to see how your version looks in [Gnome's App Icon preview](https://flathub.org/apps/details/org.gnome.design.AppIconPreview), could you post screenshot or alternatively the svg file?

**Comment by jcrows** [comment]
> 
> 
> I reiterated on my suggestion to integrate it a bit better with the Adwaita design language:
> 
> ![g2813](https://user-images.githubusercontent.com/8426567/82193537-0c543780-98e5-11ea-8402-77b7ec9a3722.png)

I like option (b) 👍

**Comment by smonsays** [comment]
> @smonsays I'd like to see how your version looks in Gnome's App Icon preview, could you post screenshot or alternatively the svg file?

Sure! Here is option (b) for example:

![Screenshot from 2020-05-19 12-33-00](https://user-images.githubusercontent.com/8426567/82316392-3e849880-99bc-11ea-902a-89220ba5e497.png)

**Comment by kbengs** [comment]
I like smonsays option (d) best. It somewhat reminds about the current icon, which might be a good thing.

**Comment by vincekd** [comment]
B or C would be my pick. I think the straight text is better, though maybe less stylish, than the angled text in D. If Option A didn't have letters on the two background books I'd also think that was fine. 

Thanks @smonsays!

**Comment by JBrummans** [comment]
> I reiterated on my suggestion to integrate it a bit better with the Adwaita design language:
> 
> ![g2813](https://user-images.githubusercontent.com/8426567/82193537-0c543780-98e5-11ea-8402-77b7ec9a3722.png)

I like either B or D :)

**Comment by bertob** [comment]
@smonsays A few tips for better adhering to the style:

- We generally try to avoid rotated objects when possible, because diagonal lines can't be aligned with the pixel grid
- It feels weird that the bottom part on the paper stacks is a different color than the front
- The rounded text lines feel a bit out of style, I'd suggest looking at how e.g. the Evince icon does it (no radius, blocks of text rather than individual lines)
- I'd "rebase" the colors on the ones from the GNOME palette. They don't have to be exactly the same, but it's nice if they have a similar feel (e.g. Foliate has an off-palette Cyan, but it still fits in in terms of saturation and brightness)

**Comment by smonsays** [comment]
Thanks for the feedback!
I agree with @bertob that we should adhere to the Gnome colour palette and that the rounded text lines feel a bit out of style. Based on the feedback so far suggestion (b) and (d) were the most popular. I added an option (e) that would avoid rotation as @bertob  suggested.
![g2813](https://user-images.githubusercontent.com/8426567/83192490-241d8e00-a125-11ea-9d3d-16cce3758744.png)

**Comment by heychrisd** [comment]
> Another variant:
> 
> ![image](https://user-images.githubusercontent.com/1908896/82151529-2990f380-985c-11ea-974a-0b93f16d303e.png)

I love this concept, because the documents are very simple and is very Adwaita stylish. Maybe if you remove the arrows? Maybe a scissor instead?... Or nothing at all?

**Comment by heychrisd** [comment]
> Thanks for the feedback!
> I agree with @bertob that we should adhere to the Gnome colour palette and that the rounded text lines feel a bit out of style. Based on the feedback so far suggestion (b) and (d) were the most popular. I added an option (e) that would avoid rotation as @bertob suggested.
> ![g2813](https://user-images.githubusercontent.com/8426567/83192490-241d8e00-a125-11ea-9d3d-16cce3758744.png)
> 
> And here would be the App Icon preview for (d):
> ![Screenshot from 2020-05-28 22-56-26](https://user-images.githubusercontent.com/8426567/83193043-f127ca00-a125-11ea-86fe-5849b3b6b20c.png)

I think last one (e) is the best because respect the common grid of Adwaita style and looks more "authentic" or "compact" with the rest of GNOME icons. :)

**Comment by merwok** [comment]
Really like the one with arrows!  It adds something to convey the edit part, compared to the other proposal which looks very similar to generic document reader icon.

**Comment by jcrows** [comment]
What if simonsays' option (e) had one of the background docs rotated and some arrows like botob's icon? I like the colours and 3d effect from simonsays icon.

**Comment by smonsays** [comment]
> I think last one (e) is the best because respect the common grid of Adwaita style and looks more "authentic" or "compact" with the rest of GNOME icons. :) The others seems unbalanced, with no defined focus.

I agree with @heychrisd in this regard and iterated on suggestion (e):
![Screenshot from 2020-05-30 13-50-41](https://user-images.githubusercontent.com/8426567/83327542-2c341580-a26c-11ea-9ca5-c1b65a396396.png)

**Comment by logari81** [comment]
Hi all,

as the creator of the old icon, I will vote for (d) which is a really good
improvement of the original idea. Having a stack of documents as in (e)
looks boring and contentless in my opinion. It doesn't provide any hint on
what to do with this stack of pages. I don't think that adding an arrow
would help either.

Best regards
Kostas

**Comment by kbengs** [comment]
Smonsays option (d) with the "Adwaita colors" I think looks really good. I think the icon says: "We are playing with pdf pages as easy as with playing cards" :-)

**Comment by jeromerobert** [comment]
Thank you all. Let's go with (d). @smonsays  could we have the `.svg` ?

**Comment by bertob** [comment]
@smonsays nice, these are better!

One thing I'd still suggest fixing is the different colors on the bottom of the paper stacks (i.e. make the light gray part the same color as the top part). You could also just drop the "chin" on the three pages entirely.

The shuffle arrow idea is neat, I'd definitely keep that in whatever you go with as the final one.

**Comment by smonsays** [comment]
Alright, here is the most recent version of option (d). As @bertob suggested, I also offer a version where the chin has the same colour as the pages themselves.
![g4086](https://user-images.githubusercontent.com/8426567/83493549-71428c80-a4a4-11ea-8b1a-4b2bdc89e566.png)

@jeromerobert : Should I just open a pull request replacing the icons in `./data/` once we come to a final decision?

**Comment by jcrows** [comment]
I vote for the dark chin

**Comment by jeromerobert** [comment]
> @jeromerobert : Should I just open a pull request replacing the icons in `./data/`

@smonsays Yes please.

> once we come to a final decision?

I think we have ;-).

**Comment by jeromerobert** [comment]
Closed by 497a30efd41fdaea794f22e4ac59429125ea7825
