### ISSUE TITLE
AttributeError: module 'img2pdf' has no attribute 'AlphaChannelError'

### ISSUE THREAD

**Issue by kbengs** [jeromerobert/pdfarranger#208]
In Kubuntu 19.10
img2pdf installed with sudo apt install img2pdf
img2pdf version 0.3.2-1

python3 -m pdfarranger
WARNING:root:Image contains transparency which cannot be retained in PDF.
WARNING:root:img2pdf will not perform a lossy operation.
WARNING:root:You can remove the alpha channel using imagemagick:
WARNING:root:  $ convert input.png -background white -alpha remove -alpha off output.png
Traceback (most recent call last):
  File "/home/kbengs/Programmering/Python/pdfarranger/pdfarranger/pdfarranger.py", line 1625, in __init__
    f.write(img2pdf.convert(filename))
  File "/usr/lib/python3/dist-packages/img2pdf.py", line 1319, in convert
    rawdata, kwargs['colorspace'], kwargs['first_frame_only']):
  File "/usr/lib/python3/dist-packages/img2pdf.py", line 863, in read_images
    imgdata, imgformat, default_dpi, colorspace, rawdata)
  File "/usr/lib/python3/dist-packages/img2pdf.py", line 676, in get_imgmetadata
    raise Exception("Refusing to work on images with alpha channel")
Exception: Refusing to work on images with alpha channel

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kbengs/Programmering/Python/pdfarranger/pdfarranger/pdfarranger.py", line 1321, in sw_dnd_received_data
    pageadder.addpages(filename)
  File "/home/kbengs/Programmering/Python/pdfarranger/pdfarranger/pdfarranger.py", line 1668, in addpages
    pdfdoc = PDFDoc(filename, self.app.tmp_dir)
  File "/home/kbengs/Programmering/Python/pdfarranger/pdfarranger/pdfarranger.py", line 1628, in __init__
    except img2pdf.AlphaChannelError as e:
AttributeError: module 'img2pdf' has no attribute 'AlphaChannelError'

This is the file that I tried to drag:
![Screenshot from 2019-04-17 18-29-02](https://user-images.githubusercontent.com/60842129/82735904-eb00aa80-9d2d-11ea-88a9-37c1446dcb94.png)

This seems to have changed in version 0.3.4:
https://gitlab.mister-muffin.de/josch/img2pdf/commit/01022487b7fb4fd6f5c306da107902b581cb640f

**Comment by jeromerobert** [comment]
So we have the choice between:
```patch
--- a/setup.py
+++ b/setup.py
@@ -53,6 +53,6 @@ setup(
     },
     install_requires=['pikepdf>=1.7.0'],
     extras_require={
-        'image': ['img2pdf>=0.3.3'],
+        'image': ['img2pdf>=0.3.4'],
     },
 )
```
and
```patch
--- a/pdfarranger/pdfarranger.py
+++ b/pdfarranger/pdfarranger.py
@@ -1625,7 +1625,7 @@ class PDFDoc:
                         f.write(img2pdf.convert(filename))
                     uri = pathlib.Path(self.copyname).as_uri()
                     self.document = Poppler.Document.new_from_file(uri, None)
-                except img2pdf.AlphaChannelError as e:
+                except Exception as e:
                     raise PDFDocError(e)
             else:
                 raise PDFDocError(_('Image format is not supported by img2pdf'))
```
I would prefer the first one.

**Comment by kbengs** [comment]
Kubuntu 20.04 (Long time support) have version 0.3.3. But it is easy to pip3 install img2pdf and have the latest version. So first one is okay for me.
