### ISSUE TITLE
1.6.0 almost ready, please test master

### ISSUE THREAD

**Issue by jeromerobert** [jeromerobert/pdfarranger#216]
We now have a lot of (and enough ;-) ) new features in master that needs to be tested. New developments will wait for 1.7.0.

I plan to release 1.6.0 by mid-July if no annoying bugs are found by then.

**Comment by jeromerobert** [comment]
https://github.com/jeromerobert/pdfarranger/milestone/10?closed=1

**Comment by jeromerobert** [comment]
I usually prepare the release notes in the draft of the release but this has the drawback of not being publicly visible. This time I will write (and update) them here:

* Improve iconview look and feel (#201, #209)
* Support image file import (#45)
* Ask user confirmation before quit (#187)
* New application icon (#205)
* Insert pages of a PDF at drop location (#106)
* Support page drag and drop on Windows (#182)
* Support Copy/Paste from a file explorer (#182, #191)
* Recommend pikepdf >= 1.15.1 (#198)

**Comment by dreua** [comment]
Wow, we can now drop PDFs directly to the correct location and even paste a PDF file from the file explorer (nautilus in my case)! Great work @kbengs !

**Comment by kbengs** [comment]
One thing I noticed is that it is possible to save a pdf before any pages are added to iconview. It results in a pdf with 0 pages.

**Comment by dreua** [comment]
Haha, I wouldn't have thought its possible but here we go, a PDF with all the metadata but no actual pages :laughing: 
![Screenshot from 2020-06-30 10-47-38](https://user-images.githubusercontent.com/15114715/86105101-36417200-babf-11ea-84e1-3901ccc0f67a.png)

**Comment by jeromerobert** [comment]
What about saying it's a feature ? (and not a bug)

**Comment by kbengs** [comment]
Maybe it could be seen as a feature. Some errors are printed to terminal though if we try to open the file later in pdfarranger.

If you like to I could test the windows release, if I could have it somehow. Would it be any idea to release that as a beta?

**Comment by jeromerobert** [comment]
> Some errors are printed to terminal though if we try to open the file later in pdfarranger.

Hum ok. Then I disabled it (8ae51f0).

> If you like to I could test the windows release, if I could have it somehow. 

Done: https://github.com/jeromerobert/pdfarranger/releases/tag/1.6.0rc1

**Comment by kbengs** [comment]
A minor issue:
![save_text](https://user-images.githubusercontent.com/60842129/86525458-f5b37100-be8f-11ea-88fb-0ba3fff3614e.png)

The save text is too much to the left. It is only when moving mouse from left to right. Same issue on both Windows and Linux. Maybe not so easy to find the cause.

**Comment by jeromerobert** [comment]
For me it happen only if I show the tooltip of the open button before showing the save tooltip. So I guess this is related with the length of the open tooltip. We have the same bug with the *Save As* button.

**Comment by jeromerobert** [comment]
The GTK bug tracker is full of bug report about tooltip position and a recurrent message is "fixed in master, master is GTK4". So I fear this will remain like this. I plan to do some test with GTK4 for the next release.

**Comment by kbengs** [comment]
A small issue this also: "Create Folder" icon in top right corner is missing in export dialog in Windows 10

**Comment by jeromerobert** [comment]
Fixed in e2441d5

**Comment by kbengs** [comment]
If we look at for example Kate, Gedit or Windows Notepad they all have the text "Untitled" in the title bar as long as the document is not saved to disk. (and also a * if it is edited and not saved) I don't know it this would be something for Pdfarranger, "Unsaved pdf [open file1, open file2 - PDF Arranger"

This does of course not have to be in 1.6.0, I just got the idea. It could be more easy to realize how the application works if that text was added. Maybe.

**Comment by jeromerobert** [comment]
1.6.0 released.

**Comment by dreua** [comment]
I'm really curious to see if we got all the bugs in this testing effort, but in any case, thank you so much for your work @jeromerobert and @kbengs you certainly squashed a few already!

I'll try to squeeze in my downstream chores later today.
