### ISSUE TITLE
python3-pkg-resources is a dependency on Debian

### ISSUE THREAD

**Issue by SwampRabbit** [jeromerobert/pdfarranger#222]
An MX Linux 19.2 (Debian 10) user reported and issue with attempting to run pdfarranger on our recent MX-19.2 KDE beta.  

```
pdfarranger
Traceback (most recent call last):
  File "/usr/bin/pdfarranger", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```
It seems in our KDE beta we were not automatically including python3-pkg-resources.

It seems that python3-pkg-resources may need to be added to the list for Debian based distributions.  

Do not believe it is an actual issue with pdfarranger, MX, Debian, or KDE at this time though.  Thank you

**Comment by dreua** [comment]
I'm not sure this is an error in pdfarranger, which version of pdfarranger is this? (Maybe it got changed in the meantime.)

I believe the `/usr/bin/pdfarranger` file is automatically created by this code:

https://github.com/jeromerobert/pdfarranger/blob/3d3eb97a652d10bee7433c414d68a55e1c32821a/setup.py#L51-L53

For me that does not contain pkg_resources:

```python
$ cat $(which pdfarranger) # not part of the file, this is command line to easily get the contents
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from pdfarranger.pdfarranger import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

```

**Comment by dreua** [comment]
Maybe I can help track this down with some of the following information:
- pdfarranger version of the package
- link to downstream issue if present
- link to downstream packaging recipe
- contents of /usr/bin/pdfarranger on the system where the error occurs

> Do not believe it is an actual issue with pdfarranger, MX, Debian, or KDE at this time though.

What do you think is the issue then? Just a random bug in beta?

Thank you for reporting this and taking care of the package! :smiley:

**Comment by SwampRabbit** [comment]
@dreua  I don't believe there is a real issue, just maybe a undocumented dependency for Debian that may need updated in the README.

It is version 1.1.1-1 from Debian 10 (stable) so it's quite old.

Link to post on MX Linux forums: [https://forum.mxlinux.org/viewtopic.php?p=586180#p586180]

From the Debian control file (recipe):
```
Build-Depends: debhelper-compat (= 12),
               dh-python,
               python3,
               python3-distutils-extra,
               python3-setuptools
Depends: ${misc:Depends},
         ${python3:Depends},
         gir1.2-glib-2.0,
         gir1.2-gtk-3.0,
         gir1.2-poppler-0.18,
         python3-cairo,
         python3-gi,
         python3-pypdf2
```
I am going to try and build 1.4.2 which is the latest packaged for Debian and see if I can replicate pdfarranger not working unless python3-pkg-resources is installed if it is not installed automatically.

**Comment by SwampRabbit** [comment]
I have built and tested pdfarranger 1.4.2 on MX Linux 19 (Debian 10).

I needed to include two additional dependencies in order to get rid of issues:
  * python3-pkg-resources
  * libcanberra-gtk3-module

I am not sure if you'd like to update the README just yet, but I will report that these dependencies may need to be included as part of the control file (recipe) to Debian.

I'll work on pdfarranger 1.5.3 to see if that builds and operates fine as well.

**Comment by jeromerobert** [comment]
@SwampRabbit You are right pdfarranger `python3-pkg-resources` need at runtime. The `Build-Depends` section is good because it contains `python3-setuptools` which pull `python3-pkg-resources` but the `Depends` section is not. The [README](https://github.com/jeromerobert/pdfarranger/blob/master/README.md) is only about building pdfarranger and does not make difference between build time and runtime (there is no such difference when using pip). I don't plan to update it as this too specific. The next step is to report the bug to https://bugs.debian.org.

I cannot find why you would need `libcanberra-gtk3-module`. I don't have it and everything seems to work. What happen if you are missing it ?

**Comment by jeromerobert** [comment]
> The next step is to report the bug to https://bugs.debian.org

Should I do it or do you prefer to do it ?

**Comment by SwampRabbit** [comment]
I will have to rebuild it to see the message that showed when libcanberra-gtk3-module was not installed.  I will do it as soon as some time clears up today.

Please feel free to file the bug report with Debian if you would like or wait until I find out the issue with libcanberra-gtk3-module.

**Comment by dreua** [comment]
> I will have to rebuild it to see the message that showed when libcanberra-gtk3-module was not installed.

In RPM-land I can just do a `sudo rpm --erase --nodeps libcanberra-gtk3`, maybe there is something like this in apt/deb?

**Comment by SwampRabbit** [comment]
Apologies, very busy at the moment.

Without libcanberra-gtk3-module installed as a runtime depend the following is output when launching pdfarranger 1.4.2:
```
Gtk-Message: 13:33:10.146: Failed to load module "libcanberra-gtk-module"

(pdfarranger:4099): Gtk-WARNING **: 13:33:10.372: Theme parsing error: gtk.css:127:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(pdfarranger:4099): Gtk-WARNING **: 13:33:10.372: Theme parsing error: gtk.css:128:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(pdfarranger:4099): Gtk-WARNING **: 13:33:10.372: Theme parsing error: gtk.css:132:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version

(pdfarranger:4099): Gtk-WARNING **: 13:33:10.385: Theme parsing error: gtk.css:3691:13: Not using units is deprecated. Assuming 'px'.
```
This message may be limited to our MX Linux KDE version or any distro which doesn't ship libcanberra-gtk-module out of the box, the above never presented itself in our main version of MX with Xfce since we include libcanberra-gtk-module.

I will test the version 1.5.3 I just packaged within the day or next day.

**Comment by dreua** [comment]
> Package: libcanberra-gtk-module (0.30-7) 
> translates GTK+ widgets signals to event sounds
> 
> A GtkModule which will automatically hook into all kinds of events inside a GTK+ program and generate sound events from them. 
*https://packages.debian.org/en/sid/libcanberra-gtk-module*

That is certainly not functionality that pdfarranger needs or uses any more than any other GTK+ program.

Is pdfarranger working and just printing this messages or is it a crash? I just tried on a debian 10 live system and couldn't reproduce the problem there.

**Comment by SwampRabbit** [comment]
@dreua pdfarranger is working very well from my testing, the messages were just printed to the terminal.  If they are not relevant that is great, I figured I'd share and ask just in case.

I'd say at this point this issue can be closed because the python3-pkg-resources dependency was the only real issue I saw trying to use it.

Thank you both for all the help, keep up the awesome work!

**Comment by jeromerobert** [comment]
Done:
* https://bugs.debian.org/965103 (this is for pikepdf which as the same issue)
* https://bugs.debian.org/965104
