### ISSUE TITLE
Please enable these four strings to be translated

### ISSUE THREAD

**Issue by ovari** [jeromerobert/pdfarranger#223]
Please enable these four strings to be translated.

1. `PDF Arranger` (the name of the program) similar to how `GNU Image Manipulation Program` has been translated
![PDF Arranger](https://user-images.githubusercontent.com/17465872/87641553-9c9ae580-c78b-11ea-8a8a-bafbb9a9ad35.png)

2. `Maintainers and contributors`
![Maintainers and contributors](https://user-images.githubusercontent.com/17465872/87640269-d36ffc00-c789-11ea-9cec-7b9517b5054d.png)

3. `GNU General Public License (GPL) Version 3.`
![GNU General Public License (GPL) Version 3.](https://user-images.githubusercontent.com/17465872/87640763-8dfffe80-c78a-11ea-83c3-1152c0253d57.png)
a) Should this be a link to https://www.gnu.org/licenses/gpl-3.0.en.html?
b) For the French version, should the link be: https://www.gnu.org/licenses/gpl-3.0.fr.html?

4. `PDF Merging, Rearranging, Splitting, Rotating and Cropping`
![PDF Merging, Rearranging, Splitting, Rotating and Cropping](https://user-images.githubusercontent.com/17465872/87641206-1a122600-c78b-11ea-86b2-b744495cfb76.png)

What do you think?

Thank you

**Comment by jeromerobert** [comment]
* I prefer to keep 1 untranslated
* I'll do the change for 2 and 3
* 4 can already be translated in [data/com.github.jeromerobert.pdfarranger.desktop](https://github.com/jeromerobert/pdfarranger/blob/master/data/com.github.jeromerobert.pdfarranger.desktop)

**Comment by jeromerobert** [comment]
Oops, actually 1 can already be translated in the same file as 4.

**Comment by jeromerobert** [comment]
59aa4fe
