### ISSUE TITLE
img2pdf

### ISSUE THREAD

**Issue by ovari** [jeromerobert/pdfarranger#225]
Can [img2pdf](https://gitlab.mister-muffin.de/josch/img2pdf) please be included when pdfarranger is installed?

Does the licences allow this?

Linux Mint 20 Software Manager shows img2pdf 0.3.3 (released 2 years ago). The current version of img2pdf is [0.3.6](https://gitlab.mister-muffin.de/josch/img2pdf/tags) (released 3 months ago).

What do you think?

Thank you

**Comment by jeromerobert** [comment]
> Can img2pdf please be included when pdfarranger is installed?

Yes it can. `pip3 install pdfarranger[img2pdf]` should work. Hopefully distribution packages will add img2pdf as a dependency when switching to 1.6.0. Note that as it's optional they may decide not to add it (or add it but make it optional if the package manager support optional dependencies). As I write this:
* It's already included in the Windows packages
* It's not yet in the FlatHub
* It's not explicit in Arch (and derivatives) but should work if img2pdf is manually installed
* It's not explicit in Fedora (and derivatives) but should work if img2pdf is manually installed
* Other distro do not have 1.6.0 yet

See https://github.com/jeromerobert/pdfarranger/wiki/Binary-packages for details.

> Linux Mint 20 Software Manager shows img2pdf 0.3.3 (released 2 years ago)

That won't work (see #208). The package maintainers should either package a new version of img2pdf or patch pdfarranger as in #208.

**Comment by dreua** [comment]
@jeromerobert How do you think about adding a note for packagers to the release notes? That would have reminded me, at least, to add img2pdf as dependency.

I'm working on getting it in FlatHub and Fedora.

**Comment by ovari** [comment]
Should this issue be closed now, once it is available in FlatHub and Fedora, once it is in Arch, or something else? Thank you

**Comment by ovari** [comment]
Can the person who packages Arch please be advised of this issue? Thank you
