### ISSUE TITLE
Update `Unknown` to the author

### ISSUE THREAD

**Issue by ovari** [jeromerobert/pdfarranger#227]
Screenshot below taken with [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal). Under `PDF Arranger` is written `Unknown`. Can `Unknown` please be updated with the author?

![PDF Arranger](https://user-images.githubusercontent.com/17465872/87773482-8ca40400-c866-11ea-8443-b33e257a7bbe.png)

What do you think?

Thank you

**Comment by dreua** [comment]
This can be set in the Appdata, but I wasn't sure who the author would be, so I just left it out. I mean, Jérôme, you are the #1 in [Github's Contributor Ranking](https://github.com/jeromerobert/pdfarranger/graphs/contributors) and the maintainer so if you want to put you name in there go ahead, but it's not my decision to make and I probably wouldn't if I were in this position. We can call it the "PDF Arranger Team" but that wouldn't add much value would it? Or should we take the top 4 contributors for example? It just seemed easier to leave it empty and I honestly thought it wouldn't be that important to anyone.

Also it's not that uncommon on Flathub to have no developer displayed:

- https://flathub.org/apps/details/org.kde.ark
- https://flathub.org/apps/details/org.filezillaproject.Filezilla
- https://flathub.org/apps/details/org.nicotine_plus.Nicotine
- https://flathub.org/apps/details/org.gnome.Notes
- https://flathub.org/apps/details/org.kde.okular
- https://flathub.org/apps/details/org.nextcloud.Nextcloud
- https://flathub.org/apps/details/org.nongnu.gsequencer.gsequencer
- https://flathub.org/apps/details/org.remmina.Remmina

... to name a few

**Comment by jeromerobert** [comment]
Thank you @dreua. I don't want to name any developer here. The only fair and up to date source for this information is https://github.com/jeromerobert/pdfarranger/graphs/contributors. I also though about something like "PDF Arranger Team" but as you say it does not add value. Now that you show that many other project do not fill that field I think we should do the same. By the way, displaying "unknown" for an unset field is a [choice of Flatseal](https://github.com/tchx84/Flatseal/blob/3ac7455b27af125993b8915181585af62d18d65e/src/models/applications.js#L172). It's not in pdfarranger nor flatpak nor AppStream. So I'm closing that issue.
