### ISSUE TITLE
Proper Windows builds (Installer etc.)

### ISSUE THREAD

**Issue by carlos22** [jeromerobert/pdfarranger#23]
Meld is also pygobject based and offers a windows installer.
Installer: https://ftp.gnome.org/pub/GNOME/binaries/win32/meld/3.18/ (requires [vcredist 2010 SP1](http://www.microsoft.com/download/en/details.aspx?id=26999))
Appveyor file: https://gitlab.gnome.org/GNOME/meld/blob/3.18.2/appveyor.yml
Setup file: https://gitlab.gnome.org/GNOME/meld/blob/3.18.2/setup_win32.py

Not sure if poppler of pygi-aio is working correctly.

This might be a way to go? The current approach using msys2 is good for developers but not very useful for the average user.

**Comment by jeromerobert** [comment]
Meld is using [cx-Freeze](https://cx-freeze.readthedocs.io/en/latest/faq.html) and `bdist_msi`. The most credible alternative I found is [pyinstaller](https://pyinstaller.readthedocs.io).

**Comment by carlos22** [comment]
pyinstaller looks also good. I think the main problem with windows are the required glib/gobject stuff. Not sure if we can use msys2 stuff also for the installer, the meld people used pygio-aio - but that is 1.5 years without updates. msys2 is more up-to-date.

**Comment by carlos22** [comment]
Never tried it, most of the examples with cx_freeze or pyinstaller are with other python distributions.
