### ISSUE TITLE
Add a "how to translate" README

### ISSUE THREAD

**Issue by jeromerobert** [jeromerobert/pdfarranger#230]
I'm missing the information on *how* to translate, I think this could go in a `po/README.md` (to be created) and linked here to not overload the the main Readme and maximize visibility for potential translators. Some information that it should contain (untested from the top of my head):
- Install from a local git checkout with your translation: `pip3 install --user .` (The dot at the end is important, run in the checked out root directory. I'd recommend to uninstall other pdfarranger packages beforehand but keep the dependencies.)
- Previous command must be re-run after each source change to take effect.
- Test different languages: `LANG="xx_YY" pdfarranger` (You may need to add `~/.local/bin/` to you PATH or just run it directly from there.)
- You may want to uninstall pdfarranger after testing and re-install your distro's package for automatic updates: `pip3 uninstall pdfarranger`
- Displayed name and description can be translated in the desktop file.
- Some explanation about the underscores and how to use them (TBD). Only use them in strings where the english version also contains an underscore.

_Originally posted by @dreua in https://github.com/jeromerobert/pdfarranger/pull/229#issuecomment-660672434_

**Comment by ovari** [comment]
Should https://github.com/jeromerobert/pdfarranger/blob/master/data/com.github.jeromerobert.pdfarranger.desktop also be added to the files that should contain translations?

**Comment by ovari** [comment]
Can https://github.com/jeromerobert/pdfarranger/blob/master/data/com.github.jeromerobert.pdfarranger.metainfo.xml be translated too?

**Comment by dreua** [comment]
### Desktop file
Yes, I already included that but in a very short form: "Displayed name and description can be translated in the desktop file." This should obviously be expanded and include a link to the actual file.

### Metainfo
Good catch, yes that can also be translated. Here is a random example from my harddrive: 
[network-manager-pptp.metainfo.xml.txt](https://github.com/jeromerobert/pdfarranger/files/4958802/network-manager-pptp.metainfo.xml.txt) (Yikes, Github does not allow .xml files to be attached.)

This is what it looks like. Note that most lang identifiers are two letter codes, but there is also `fur`, `pt_BR` and `sr@latin`. Research/Testing is needed to make sure this is compatible with the codes we use at the moment.
```xml
    <p>Compatible with various PPTP servers including Microsoft.</p>
[...]
    <p xml:lang="fur">Compatibil cun varis servidôrs PPTP includût Microsoft.</p>
    <p xml:lang="hr">Kompatibilno s raznim PPTP poslužiteljima uključujući Microsoft.</p>
    <p xml:lang="hu">Kompatibilis különböző PPTP kiszolgálókkal, beleértve a Microsoftot.</p>
    <p xml:lang="id">Kompatibel dengan berbagai server PPTP termasuk Microsoft.</p>
    <p xml:lang="it">Compatibile con molteplici server PPTP compresi quelli Microsoft.</p>
    <p xml:lang="lt">Suderinama su įvairiais PPTP serveriais, įskaitant Microsoft.</p>
    <p xml:lang="lv">Savietojams ar dažādiem PPTP serveriem, tai skaitā Microsoft.</p>
    <p xml:lang="nl">Compatibel met verscheidene PPTP-servers, inclusief Microsoft.</p>
    <p xml:lang="pl">Zgodne z różnymi serwerami PPTP, w tym firmy Microsoft.</p>
    <p xml:lang="pt_BR">Compatível com servidores PPTP, incluindo Microsoft.</p>
    <p xml:lang="ru">Совместим с различными серверами PPTP, включая Microsoft.</p>
    <p xml:lang="sr">Сагласно са и разним ППТП серверима укључујући и Мајкрософт.</p>
    <p xml:lang="sr@latin">Saglasno sa i raznim PPTP serverima uključujući i Majkrosoft.</p>
```
Not sure what this is for:
```xml
  <translation type="gettext">NetworkManager-pptp</translation>
```


### Tooling
In theory it should be possible to translate both files via po files only, but I don't know whether this is worth the effort for us. https://www.freedesktop.org/software/appstream/docs/sect-Quickstart-Translation.html (This is about the metainfo, but I'm quite sure I've seen ...desktop.in files as well.)
If desktop and metainfo are translated by hand, doing syntax checks via CI would be a good idea.

**Comment by jeromerobert** [comment]
501c468

* I contacted Gnome translators on IRC about guildine for mnemonics accelerators (https://github.com/jeromerobert/pdfarranger/pull/221#issuecomment-658602874). I'm waiting for an answer.
* I didn't go into details about `metainfo.xml` translation as we have no experience about it.

Now I'm thinking about closing this issue, unless you have things to add.

**Comment by dreua** [comment]
Looks good to me, thank you! I agree that this can be closed now.
