### ISSUE TITLE
Rename Windows binary from mingw.{zip,msi} to windows.{zip,msi}

### ISSUE THREAD

**Issue by dreua** [jeromerobert/pdfarranger#232]
Do I understand correctly that mingw is only used to build pdfarranger and Windows users don't need to install it themselves just to use pdfarranger? In this case I'd suggest to rename the binaries in future releases to make it easier for users to identify the correct download.

I wonder if additionally the Readme could be improved to guide regular (i.e. non-developer) users to the installation, a few ideas:
- "Binary packages" may not be understood. Something like Download or Install Pdfarranger might be more widely used. Maybe even a big green button with down arrow or a package symbol.
- Avoid the extra step through the wiki page: Windows users could be send straight to "Releases", available Linux packages could be displayed as a Repology badge, [eigher on the right](https://github.com/dreua/pdfarranger/blob/patch-1/README.md) or [with multiple columns](https://repology.org/badge/vertical-allrepos/pdfarranger.svg?columns=3). Installation methods for all linux distros (Flatpak and pip) should be mentioned.
- Explain the difference between zip and msi.

**Comment by jeromerobert** [comment]
I often see *portable* for zip files in the Windows world. Would `pdfarranger-windows-installer-version.msi` and `pdfarranger-windows-portable-version.zip` be explicit enough ?

**Comment by dreua** [comment]
That would be perfect!

**Comment by jeromerobert** [comment]
In progress: cb6d018

**Comment by jeromerobert** [comment]
And the second part: 18fc459
