### ISSUE TITLE
[Feature request] Utilizing OCRmyPDF backend !

### ISSUE THREAD

**Issue by Nokia808** [jeromerobert/pdfarranger#238]
Hi.
There is a very powerful command line program which can perform "Optimize scanned PDF" as following:

Deskew (correction of slopping)
Descreen (remove black dots noises)
Remove background
Text sharpening (text enhancement: make text more clear)
centralize (make content image at middle of page so that left white margin will be equal to right white margin of the page)
OCR PDF

OCRmyPDF depend on QPDF + pikepdf.
Sites of OCRmyPDF:
https://pypi.org/project/ocrmypdf/
&
https://github.com/jbarlow83/OCRmyPDF
Sites of pikepdf:
https://pikepdf.readthedocs.io/en/latest/
&
https://github.com/pikepdf/pikepdf
Note: pikepdf has abilities to re-size the pages of PDF, also, so it could be helpful for #24 (closed)
Bellow are screenshots from Windows programs have optimize scanned PDF functionalities (centralize contents not included):

![optimize-scanned-pdf-1](https://user-images.githubusercontent.com/25375330/88385001-112ddf80-cd9d-11ea-9b1a-23e8e522f697.PNG)

![optimize-scanned-pdf-2](https://user-images.githubusercontent.com/25375330/88385011-17bc5700-cd9d-11ea-9009-2ada037d99db.PNG)

Adding this feature will full a big gab in GUI management of PDF files on Linux OS ...

Thank you.

**Comment by jeromerobert** [comment]
Similar to #45 but with much more dependencies (ex: tesseract)

I won't develop nor maintain that feature but if someone do it and manage to make the dependencies (all of them) optional (in the python code and in the setup.py), I'll integrate his work.

**Comment by jeromerobert** [comment]
As I'm sure that no one is going to work on this feature, I'm closing that issue.

**Comment by rugk** [comment]
I know you argue tesseract should not be a dependency of the project, I think a big plus here is you already depend on pikepdf, which [is also used by _OCRmyPDF_](https://github.com/pikepdf/pikepdf/?tab=readme-ov-file#in-production), so some dependencies are already there.

And, IMHO, it just fits into a PDF editor tool in the wider sense to at least have an optional integration. E.g. for the _flatpak_ [this could even be packaged as a separate extension](https://docs.flatpak.org/en/latest/extension.html) you can install separately.

Related suggestions for similar tools: 
- https://gitlab.com/scarpetta/pdfmixtool/-/issues/26
- https://github.com/junrrein/pdfslicer/issues/76 (PDFSlicer seems outdated/unmaintained)

More or less meta-issue: https://github.com/ocrmypdf/OCRmyPDF/issues/399
