### ISSUE TITLE
"Save" option bahaving as "Save as" option !

### ISSUE THREAD

**Issue by Nokia808** [jeromerobert/pdfarranger#243]
Hi. 

When I used "Save" option it behave as if "Save as" option:
- show me window with file name, & ability to navigate to new directory .....,
- ask "a file named ...... currently exist, do you like to replace it?"

This is not "Save" behaviour ! By clicking on "Save" option it should replace file by new version without this windows & question ... QPDF version 9.0.0 & above has such option by the following command line "--replace-input" - see change log of QPDF at:
http://qpdf.sourceforge.net/files/qpdf-manual.html#ref.release-notes

The --replace-input option may be given in place of an output file name. This causes qpdf to overwrite the input file with the output. See the description of --replace-input in Section 3.3, “Basic Options” for more details.

**Comment by dreua** [comment]
This is a duplicate. Should be easy to finde in the (previously) 11 open issues...

**Comment by jeromerobert** [comment]
Duplicate #100
