### ISSUE TITLE
"Past after" & "Past special" options should be inactive if no "Cut" or "Copy" action already done.

### ISSUE THREAD

**Issue by Nokia808** [jeromerobert/pdfarranger#245]
Hi.

I noticed that, currently, "Past after" & "Past special" options are always active in right click list even if user did not perform "Cut" or "Copy" option ! This is not correct ! These past options should only be active after user perform "Cut" or "Copy" operations. Otherwise, they should appearing in right click list as  inactive

**Comment by jeromerobert** [comment]
f45bd7f19cdd3e5bace8786b655d2e4c8489a2a7
