### ISSUE TITLE
"Save as" failing

### ISSUE THREAD

**Issue by wacka3333** [jeromerobert/pdfarranger#249]
opening "200207_aktionstag_geodaesie_infoblatt.pdf"(google), rotating the second page topsy turvy, try save as:
Result-Mesage:
"not all arguments converted during string formatting"
Closed with OK- button, nothing has been saved, without notice that nothing has been saved.
So if you dont controll, you maybe lost data.

Version 1.1 in
Desktop: Xfce 4.14.2 tk: Gtk 3.24.5 info: xfce4-panel wm: xfwm4 dm: LightDM 1.26.0 
           Distro: MX-19.2_x64 patito feo May 31  2020 base: Debian GNU/Linux 10 (buster)

**Comment by jeromerobert** [comment]
This was more likely fixed a year ago (pdfarranger 1.3) when switching to pikepdf. And even if we would manage to do a fix for a so old version there is few chance that would enter in Debian Buster (not critical enough). So I'm closing this bug as "won't fix".

I would advice to use pdfarranger 1.6.0 (with pikepdf installed by pip so it's not too old). You may also use the flatpak package.
