### ISSUE TITLE
Add "Combine" beside "Append" option.

### ISSUE THREAD

**Issue by Nokia808** [jeromerobert/pdfarranger#251]
Hi. 

Currently, pdfarranger has ability to append multiple PDF (or even images) to one other, so that output it will be single output PDF. This is very excellent !

However, current "Append" option result - after it's applying - to visualize (as a thumbnails) all pages of all appended files. This of no problem if we deal with images. But if we deal with many PDF files, each of them composed of say 100 pages, then this may be not suitable for many users because all needed may be seeing the arrangement of book files (NOT their internal pages) with ability to rearrange them (move up / down).

For that I would like to suggest to add new option "Combined" so that after applying it, only the parent multipages files (their names & icons for them like their cover icons) appearing without their internal pages & their within UI 2 options one for move up & 2nd for move down, so that user can re-arrange them .... 

If you accept to add this feature, leave the current "Append" option as it without touching it, & make new options working on both PDF files & images (no problem to work on both PDF & image files) ...

**Comment by jeromerobert** [comment]
No sorry we won't do that. pdfarranger is a tool. pdfmixertool is another tool.

**Comment by Nokia808** [comment]
@jeromerobert 
No not that ! I just like the Linux system to have some all-in-one or almost all-in-one PDF editor tool.
Please do not misunderstand me !

**Comment by jeromerobert** [comment]
pdfarranger does not aims at being a all-in-one editor.
