### ISSUE TITLE
Packaging 1.6.1, error in Desktop file: 'file contains key "Categories[hu]"'

### ISSUE THREAD

**Issue by dreua** [jeromerobert/pdfarranger#253]
```
$ desktop-file-validate data/com.github.jeromerobert.pdfarranger.desktop 
data/com.github.jeromerobert.pdfarranger.desktop: error: file contains key "Categories[hu]" in group "Desktop Entry", but "Categories" is not defined as a locale string
```

Will there be a quick 1.6.2 or do I need to patch this in packaging? 

[The desktop file spec](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#idm46567123448352) defines Categories as Strings, not as localestrings. It seems like it should usually be a list of (english) Keys for already registered categories, which I assume will be translated elsewhere. See also:
- https://specifications.freedesktop.org/menu-spec/latest/ar01s03.html#desktop-entry-extensions-examples
- https://specifications.freedesktop.org/menu-spec/latest/apa.html

(I actually had the [precognition](https://github.com/jeromerobert/pdfarranger/issues/230#issuecomment-662351499) that checking metadata in CI would be useful.)

**Comment by jeromerobert** [comment]
> Will there be a quick 1.6.2 or do I need to patch this in packaging?

Yes, I'll do it today or tomorrow.

**Comment by dreua** [comment]
@jeromerobert for some reason I can't see the 1.6.2 in my local checkout, have you forgotten to push the latest master? Fedora und openSuse is building now, thanks for the quick fix and already taking care of the CI!

**Comment by jeromerobert** [comment]
1.6.2 is not in master because I do not want fd5dbb23880ff9be8db437d27b793683d6b1a013 in 1.6.2. 1.6.2 is on a not named branch. `git fetch -t && git log --graph --all` will show it.

**Comment by dreua** [comment]
Alright makes sense. Yeah it seems that my tools don't fetch or show tags which aren't in branches by default. Thanks for the clarification!

**Comment by dreua** [comment]
For the record: If your default remote is not this repository, you need to fetch tags explicitly for the correct remote. For me the default remote (origin) is my fork and this repo is `upstream` so I needed to do `git fetch upstream --tags` to get this tag and the commit. My usual `git remote update` was not sufficient.
