### ISSUE TITLE
[Feature request] Add support for encryption functionalities

### ISSUE THREAD

**Issue by Nokia808** [jeromerobert/pdfarranger#257]
Hi.
QPDF contain very powerful encryption functions - see bellow link:
http://qpdf.sourceforge.net/files/qpdf-manual.html#ref.encryption-options

It is useful to have GUI for these functionalities through pdfarranger. 

I would like to suggest the following UI:

1) like "Edit properties", the proposed "Encryption" options should be in the same upper right gear list,
2) "Encryption" options should be just above "Edit properties" option,
3) clicking of proposed "Encryption" option should result in new window - as for "Edit properties" - but certainly should be larger in size,
4) within new window (in point 3) there should be choices of encryption option arranged as sub-option then bellow it it's choices as check boxes, where user can check only one of these boxes like, for ex, the following (please notice that I can not draw check boxes here):

"Key length":
40 bit | 128 bit | 256 bit

"Printing":
Allowed | Disallowed
Full | low               (Note: this line should be active only if "Allowed" is checked by user & key length is set to 128 or 256 bit. It should be inactive if user set key length to 48, or if select "Disallowed")

"Document modification":
Allowed | Disallowed

"Text/image extraction":
Allowed | Disallowed

"Annotations (Comments and form fill-in and signing)":
Allowed | Disallowed

"Rotation and reordering of pages":
Allowed | Disallowed

"Accessibility to visually impaired":
Allowed | Disallowed

"Rotation and reordering of pages":
Allowed | Diallowed

"Filling form fields":
Allowed | Disallowed

And bellow all the above, there should be 2 check boxes:
[Encrypt cleartext-metadata]
[Use AES encryption will be used instead of RC4 encryption]

Lastly & bellow all above, there should be field for passwords as following:
"User password":            (to be set by user)

"Owner password":        (to be set by user)

Kindly, notice that some of these functionalities should be freeze (not be available to user) or being active (available to user) depending on key length selected. That is to say, if user slelect 48 bit key length then the following should be freeze:
"Rotation and reordering of pages"
"Accessibility to visually impaired"
"Filling form fields"
[Encrypt cleartext-metadata]
[Use AES encryption will be used instead of RC4 encryption]

But if user select key length to be 128 bit then, all parameter should be active & available to user.
If user select key length to be 256 bit, then also all parameter should be active & available but [Use AES encryption will be used instead of RC4 encryption] check box must be enforcedly checked .....

**Comment by Nokia808** [comment]
Note: if the PDF is already not encrypted, then the above suggested UI should opened directly without asking any password(s). But if PDF file is already encrypted by User password/Owner password then the program should asking (when try to use "encryption" proposed new function) for User password/Owner password accordingly before allowing the suggested user interface to appear.

**Comment by jeromerobert** [comment]
@Nokia808  We are not an IT service company but just individual working on this project as a hobby. Please stop openning issue containing specifications. It takes to much time to read (actually when I see you open an issue I just read the title). As not being a developer you are not able to write specifications. Thus even if encryption support is something I have in mind and I'll do one day I'm closing this issue as it contains mostly noise. Now please stop openning feature requests. We can't have all feature requests comming from the same guy.

**Comment by parrenin** [comment]
Sorry to come back to this old issue, but is PDF encryption still in the radar?
On Linux, you can do PDF encryption on the command line, but I don't see a nice graphical app to do that.
There is PDFchain but it does not seem to be maintained anymore.

**Comment by dreua** [comment]
It is not exactly a good argument here to mention that others how have implemented it subsequently seem to have given up :wink: 

It's not on my radar, I'd never use it myself. I really don't see the point in PDF encryption from an infosec perspective, leaving the most likely explanations for people using it to lack of knowledge or implementation of questionable compliance policies. Not stuff I'd spend time on voluntarily.

Jerome hasn't been very active lately, so no, it's probably not on our radar, sorry.

**Comment by parrenin** [comment]
A drive (either local or in the cloud) could be compromised by a malicious application or an attack.
I see PDF encryption as a extra layer of security for sensible documents (e.g., ID, health documents, official documents, etc.)

**Comment by digidigital** [comment]
> Sorry to come back to this old issue, but is PDF encryption still in the radar? On Linux, you can do PDF encryption on the command line, but **I don't see a nice graphical app** to do that. There is PDFchain but it does not seem to be maintained anymore.

@parrenin - You can argue about whether the GUI is “nice”, but there is a fronted for pikepdf -> qpdf I hacked together some time ago that does what you want -> https://github.com/digidigital/AESify

Otherwise I think there are valid use cases for encryption and decryption in PDF Arranger. E. g. for data protection reasons our company has to encrypt all PDF files we send via E-Mail. Therefore we have to encrypt and the receiver has to decrypt. The encryption and decryption part are premium features in commercial software when in fact pikepdf / qpdf makes implementing those functions a breeze. 

Obviously the de- and encryption capabilities are already there. What's missing is a predictable way to configure them (set open & permissions password, set permissions) in the main menu.

**Comment by parrenin** [comment]
@digidigital: thanks for the information about AESify.
It does the job, but it would be nice to have a gtk+ interface.
Looking forward to having this implemented in PDF Arranger.
