### ISSUE TITLE
Add option to deskew a single page

### ISSUE THREAD

**Issue by angsch** [jeromerobert/pdfarranger#259]
Hi!

When a document it not perfectly aligned during the scan process, the document's text is rotated with a small angle. Deskewing rotates the page to align the content correctly.

I see two options to add a deskew feature. (1) A user selects a page for deskewing and adjusts the angle manually. (2) Alternatively, one could aim for a more automatic processing, let's call it an option for automatic improvement. This could cover autodeskewing and, later on, can be extended to, for example, crop black scan margins or remove skewing from slightly bent book pages during the scan process.

Best,
angsch

**Comment by Nokia808** [comment]
@angsch 
Hi. See the following:
https://github.com/jeromerobert/pdfarranger/issues/238

Can you perform the re-write of OCRmyPDF & it's dependencies to python ?

**Comment by angsch** [comment]
@Nokia808 
Hi, thanks for referring to that issue. Rewriting all of OCRmyPDF is a huge project. What I had in mind in my proposal is a much simpler. I think that _manual_ deskewing is possible with qpdf functionality. Option (2) primarily concerns the choice of the user interface, leaving it open to add functionality if qpdf progresses in a direction such that image manipulation is possible more easily.

**Comment by Nokia808** [comment]
@angsch 
No ! I think - in fact I'm sure - developer of QPDF will not implement what you dreaming, because I dreamed the same dream (or in fact bigger dream than your dream) & asked him about it too long before your asked here - see my request bellow:
https://github.com/qpdf/qpdf/issues/111

**Comment by jeromerobert** [comment]
@angsch Sorry free angle rotation is not supported by qpdf so it's not supported by pikepdf, so we won't do that.
