### ISSUE TITLE
gtk3 and gtk3-classic are in conflict

### ISSUE THREAD

**Issue by stavpup** [jeromerobert/pdfarranger#29]
Arch / manjaro

~ >>> sudo pacman -S poppler-glib gettext python-pip python-gobject gtk3 python-cairo

warning: poppler-glib-0.71.0-1 is up to date -- reinstalling
warning: gettext-0.19.8.1-3 is up to date -- reinstalling
warning: python-gobject-3.30.1-3 is up to date -- reinstalling
warning: python-cairo-1.17.0-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...
:: gtk3 and gtk3-classic are in conflict (gtk3-print-backends). Remove gtk3-classic? [y/N] n
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: gtk3 and gtk3-classic are in conflict

**Comment by dreua** [comment]
It seems that you [cannot install gtk-3 and gtk-3 classic at the same time](https://forum.manjaro.org/t/unstable-gtk3-classic-and-gtk3-are-in-conflict-remove-gtk3/35602/7) and you already have gtk3-classic installed. Have you tried using pdfarranger with gtk3-classic? I think gtk3-classic is just another theme so it might just work.

**Comment by stavpup** [comment]
The menu entry pdfarranger does not work.
Also

`~/.../site-packages/pdfarranger >>> python pdfarranger.py

(pdfarranger.py:3612): Gtk-WARNING **: 22:15:42.986: Theme parsing error: gtk-dark.css:2077:4: Junk at end of value for border-left-color
Traceback (most recent call last):
  File "pdfarranger.py", line 92, in <module>
    from .iconview import CellRendererImage
ModuleNotFoundError: No module named '__main__.iconview'; '__main__' is not a package
`

**Comment by dreua** [comment]
This error is unrelated to Gtk, please try to run the `bin/pdfarranger` file. For me on Fedora this is installed to `~/.local/bin/pdfarranger` and therefore I can just run `pdfarranger` in the commandline.
How did you install pdfarranger?

**Comment by stavpup** [comment]
> This error is unrelated to Gtk, please try to run the `bin/pdfarranger` file. For me on Fedora this is installed to `~/.local/bin/pdfarranger` and therefore I can just run `pdfarranger` in the commandline.
> How did you install pdfarranger?

I followed the instructions;

sudo pacman -S poppler-glib gettext python-pip python-gobject gtk3 python-cairo
Then:

pip install --user -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt

**Comment by dreua** [comment]
Ok, what about the other pointers I gave you? Have you tried running `~/.local/bin/pdfarranger`?
Can you post the result of `echo $PATH`? Maybe `/home/<user>/.local/bin`is not included so the `pdfarranger` command and the desktop file won't work.

**Comment by stavpup** [comment]
> Ok, what about the other pointers I gave you? Have you tried running `~/.local/bin/pdfarranger`?
> Can you post the result of `echo $PATH`? Maybe `/home/<user>/.local/bin`is not included so the `pdfarranger` command and the desktop file won't work.

There are binaries in these dirs

**Comment by dreua** [comment]
Well there should be at least one file, maybe you need someone who knows arch / manjaro to fix this...
My best guess is that the pip install didn't work properly but I can't think of a reason why... Maybe the output of `pip uninstall pdfarranger` followed by `pip install -v --user -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt` will give me a clue. (Note the additional **-v** for verbose output.)

**Comment by stavpup** [comment]
> Well there should be at least one file, maybe you need someone who knows arch / manjaro to fix this...
> My best guess is that the pip install didn't work properly but I can't think of a reason why... Maybe the output of `pip uninstall pdfarranger` followed by `pip install -v --user -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt` will give me a clue. (Note the additional **-v** for verbose output.)

https://pastebin.com/HHYbNfh6

**Comment by dreua** [comment]
Looks good:
```
    copying build/scripts-3.7/pdfarranger -> /home/stvrs/.local/bin
    changing mode of /home/stvrs/.local/bin/pdfarranger to 755
```
Please try to run `/home/stvrs/.local/bin/pdfarranger`

**Comment by stavpup** [comment]
> Looks good:
> 
> ```
>     copying build/scripts-3.7/pdfarranger -> /home/stvrs/.local/bin
>     changing mode of /home/stvrs/.local/bin/pdfarranger to 755
> ```
> Please try to run `/home/stvrs/.local/bin/pdfarranger`

yes it does run. :-)

(pdfarranger:21097): Gtk-WARNING **: 01:25:56.193: Theme parsing error: gtk-dark.css:2077:4: Junk at end of value for border-left-color
