### ISSUE TITLE
Icon missing

### ISSUE THREAD

**Issue by dreua** [jeromerobert/pdfarranger#30]
For me using Fedora 28 the icon of pdfarranger is missing. I think the icon path should not include `pdfarranger` other than as the filename, but I'm not sure if this is something distro specific. Thoughts? 
https://github.com/jeromerobert/pdfarranger/blob/4dcb5ef8873ff9ff3936d3cb0d49b8fb4f2ca3cf/setup.py#L27-L39
This works for me: https://github.com/dreua/pdfarranger/commit/3636f818c8edd89fc3b5265eb73b95f504b1369b

**Comment by jeromerobert** [comment]
Where did you installed ? `/usr/local` ? `$HOME/.local` ? virtualenv ?

Meld is also using the `share/appname/icons` folder (see https://gitlab.gnome.org/GNOME/meld/blob/master/setup.py) so I would assume this is correct. Where does other GTK apps install icons on Fedora 28 (when using `yum` or `rpm`) ?

**Comment by jeromerobert** [comment]
Arch Linux install to `share/icons` as you suggest (see <https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pdfshuffler-git#n36>. <https://sourceforge.net/p/pdfshuffler/bugs/37>  and <https://developer.gnome.org/integration-guide/stable> also says that it should go to `share/icons`.

But as far as I understand the current code should work. This patch should help to understand why it does not.

--- a/pdfarranger/pdfarranger.py
+++ b/pdfarranger/pdfarranger.py
@@ -126,7 +126,9 @@ class PdfShuffler:
         iconsdir = os.path.join(sharedir, DOMAIN, 'icons')
         if not os.path.exists(iconsdir):
             iconsdir = os.path.join(sharedir, 'data')
+        print("Search path before: ", Gtk.IconTheme.get_default().get_search_path())
         Gtk.IconTheme.get_default().append_search_path(iconsdir)
+        print("Search path after: ", Gtk.IconTheme.get_default().get_search_path())
         Gtk.Window.set_default_icon_name(DOMAIN)
 
         # Import the user interface file, trying different possible locations

Once we'll have understood what's going I'll apply your patch.

**Comment by dreua** [comment]
I installed to `$HOME/.local` via `pip3 install --user .` from within the pdfarranger root directory. I can try your patch but the icon is also missing in Gnome's Applications menu, which can not be affected by this python code.

**Comment by dreua** [comment]
```
Search path before: 
['/home/da/.local/share/icons',
 '/home/da/.icons',
 '/home/da/.local/share/flatpak/exports/share/icons',
 '/var/lib/flatpak/exports/share/icons',
 '/usr/local/share/icons',
 '/usr/share/icons',
 '/home/da/.local/share/flatpak/exports/share/pixmaps',
 '/var/lib/flatpak/exports/share/pixmaps',
 '/usr/local/share/pixmaps',
 '/usr/share/pixmaps']
Search path after: 
['/home/da/.local/share/icons',
 '/home/da/.icons',
 '/home/da/.local/share/flatpak/exports/share/icons',
 '/var/lib/flatpak/exports/share/icons',
 '/usr/local/share/icons',
 '/usr/share/icons',
 '/home/da/.local/share/flatpak/exports/share/pixmaps',
 '/var/lib/flatpak/exports/share/pixmaps',
 '/usr/local/share/pixmaps',
 '/usr/share/pixmaps',
 '/home/da/.local/share/pdfarranger/icons']

```

**Comment by jeromerobert** [comment]
> I can try your patch but the icon is also missing in Gnome's Applications menu

Ok, it's missing on Debian / XFCE too ! I though you were talking about the window icon, not the menu icon. I'm going to fix this.

**Comment by dreua** [comment]
Actually I was talking about both, the Window and the Menu icon.
