### ISSUE TITLE
pip install fails since usage of DistUtilsExtra.auto

### ISSUE THREAD

**Issue by dreua** [jeromerobert/pdfarranger#31]
Since https://github.com/jeromerobert/pdfarranger/commit/2077a7386af3a39252c4ed22d7eecf89b3786c5c I can not install with pip3. 
Here is a log of the failing installation (with -v): [pip_log_error.txt](https://github.com/jeromerobert/pdfarranger/files/2593218/pip_log_error.txt)
Here is a log installing the last working version (with -v): [pip_log_ok.txt](https://github.com/jeromerobert/pdfarranger/files/2593219/pip_log_ok.txt)

What I tried so far: 
- update distutils, install wheel
- remove import of pyPdf since the log says `ERROR: Python module pyPdf not found`
- Note that both versions contain `--single-version-externally-managed` but only the new doesn't recognize it.

Am I the only one having this problem?

**Comment by jeromerobert** [comment]
I can reproduce that bug with pip 9 but it works with pip 10 and pip 18, so a workaround is `pip3 install pip`. Anyway not working with pip 9 is a major issue because it's still the default in many distros.

May be this is the related bug: https://github.com/pypa/setuptools/issues/566

**Comment by dreua** [comment]
I'm sorry for forgetting to include the versions:
```
$ pip3 --version
pip 18.1 from /home/da/.local/lib/python3.7/site-packages/pip (python 3.7)
$ pip --version
pip 18.0 from /usr/lib/python2.7/site-packages/pip (python 2.7)
$ pip3 freeze | grep distutils
python-distutils-extra==2.39


```

For the workaround:
```
$ pip3 install pip
Requirement already satisfied: pip in /home/da/.local/lib/python3.7/site-packages (18.1)
```

I just installed `python3-wheel` and now I additinally get this error:
```
  error: [Errno 2] No such file or directory: 'bin/pdfarranger.py'
error
  Failed building wheel for pdfarranger

```
I tried the same with pip for Python2 environment after installing python2-wheel and python2-distutils-extra but results are the same.
Soo yeah, maybe my Python environment is messed up, maybe DistUtilsExtra.auto is... Maybe I'll try again in a venv to see if that improves anything.

**Comment by jeromerobert** [comment]
@dreua does ebf6cd0 help ? (it does for me)

**Comment by dreua** [comment]
Yeah, thats perfect, how did you come up with that?
First it gave me this `error: command 'intltool-update' failed with exit status 1` which I fixed by installing intltool from my distros repository. Now it works with python 2 and 3 :+1: 

Side note: the current master also builds with intltool installed. (I double checked, there is not a single hint that intltool might be missing when it fails.)

**Comment by jeromerobert** [comment]
> Yeah, thats perfect, how did you come up with that?

The pip bug report is saying the problem is about mixing `setuptools` and `distutils`. Then I searched <https://sources.debian.org> on how people were using DistUtilsExtra with `setuptools`.

> which I fixed by installing intltool from my distros repository

On Debian `python-distutils-extra` depends on `intltool`. May be we'll have to add/update the installation instructions for your distro.

**Comment by dreua** [comment]
Thats good to know, thanks you for your work!
I would vote to merge https://github.com/jeromerobert/pdfarranger/commit/ebf6cd0028614595bcbef5c1151b5038e5b00ca0 into master because it has a better error messages in case someone misses intltool and additionally the current master version displays some errors during build which are misleading.

My distro is Fedora. For dependencies I took the list from Arch and added wheel, intltool and pyPDF2. This should be a good starter but I can't verify correctness.
`sudo dnf install poppler-glib python-distutils-extra python-pip python-gobject gtk3 python-cairo intltool python-wheel python-PyPDF2`

For Python3:
`sudo dnf install poppler-glib python3-distutils-extra python3-pip python3-gobject gtk3 python3-cairo intltool python3-wheel python3-PyPDF2`
