### ISSUE TITLE
Release debian package

### ISSUE THREAD

**Issue by darkdragon-001** [jeromerobert/pdfarranger#35]
Please also package your release as Debian package. The original files for _pdfshuffler_ in the [Ubuntu repository](https://packages.ubuntu.com/source/disco/pdfshuffler#pdownload) might help!

**Comment by jeromerobert** [comment]
@jbicha Should I fill a [RFP](https://wiki.debian.org/RFP) or will this be managed through <https://bugs.debian.org/879034> ?

**Comment by jbicha** [comment]
I can work on the initial packaging. Feel free to ping me if it seems to be taking a while.

**Comment by darkdragon-001** [comment]
Debian patch [committed](https://salsa.debian.org/python-team/applications/pdfarranger/commit/84f3a44ba6a9cd95f722b7200da86f5e3bb43dce) 🎉

**Comment by jeromerobert** [comment]
https://tracker.debian.org/pkg/pdfarranger
