### ISSUE TITLE
Release as a Flatpak package

### ISSUE THREAD

**Issue by thecursedfly** [jeromerobert/pdfarranger#37]
Hi,

It would be great if you could package PDFarranger in a flatpak package (see https://flatpak.org/ for info/documentation).
That way non techy users would be able to install the application without having to install separate packages. I also recommend a flatpak package because it is distribution independent, avoids dependency problems and incompatibilities with older/newer Linux distribution versions, and allows sandboxing for additional security.

Thanks

**Comment by jeromerobert** [comment]
I'm not a flatpak user so it would be great that someone else would maintain and upload the pdfarranger flatpak package.

**Comment by PhillyMay** [comment]
I'd also love to see a crossplattform package. If you can't decide to maintain a flatpack image, how about an .appimage file? It works equally well on different linux distros.

**Comment by PadreAdamo** [comment]
I packaged a Flatpak for myself as I'm on OpenSUSE and that was the easiest way for me to install. Would you mind if I did this task Jerome?

**Comment by jeromerobert** [comment]
Thanks ! Here is what I had in mind:
* Upload the Flatpak to https://flathub.org
* Keep https://github.com/jeromerobert/pdfarranger/blob/master/flatpak.yaml up to date with PR if you need to modify it

**Comment by jeromerobert** [comment]
Well, if you known any alternative to flathub that will also be fine.

**Comment by jeromerobert** [comment]
@PadreAdamo I missread your question. I would be happy if you would manage pdfarranger on flathub.

**Comment by PadreAdamo** [comment]
No problem @jeromerobert, I haven't had a chance to dive in yet. I build the flatpak locally and will start this project soon I hope! You made a great tool!

**Comment by PhillyMay** [comment]
> 
> 
> No problem @jeromerobert, I haven't had a chance to dive in yet. I build the flatpak locally and will start this project soon I hope! You made a great tool!

Can't wait to see that happen. I really like the Solus OS, but it lacks a good pdf merger. On Windows I use pdf24 (great tool, sadly there is no linux version). Thats why i keep jumping between solus and manjaro.

**Comment by jeromerobert** [comment]
@PhillyMay I think Solus have all required packages so you could install pdfarranger with pip

**Comment by dreua** [comment]
What is the status here? Is there anything I can help with?

**Comment by jeromerobert** [comment]
What has not changed:

* I won't work on it
* Upload of the flatpak to https://flathub.org is still needed

What is new:

* Considering your recent work on *duplicate* pikepdf should be update in <https://github.com/jeromerobert/pdfarranger/blob/master/flatpak.yaml>
* I did not tested the `flatpak.yaml` file for a while so other changes may be needed

**Comment by dreua** [comment]
I'm working on this now, next steps (my personal Todo):

- [ ] Fix missing icon in About
- [ ] Update dependencies
- [ ] Some testing
- [ ] Request flathub repository

**Comment by dreua** [comment]
It's done, everyone interested in flatpaks please test and report if anything doesn't work. It would be great if one or two persons could help me with testing the flatpak on a regular basis (i.e. after new releases) as I already have the Fedora package and my local git checkout and switching between all of those is a bit cumbersome. (Comment here or [drop me a line](mailto:dreua@posteo.de) if you want to help.)

https://flathub.org/apps/details/com.github.jeromerobert.pdfarranger

The recipe has it's own repository:
https://github.com/flathub/com.github.jeromerobert.pdfarranger

- [ ] I think it would be a good idea to remove the flatpak.yml from this repository to protect people from using outdated stuff

**Comment by dreua** [comment]
Version 1.5.0 is released: https://github.com/flathub/com.github.jeromerobert.pdfarranger/pull/1

Should be available on the main site / via flatpak update in a few hours. Let me know if anything does not work as expected!

**Comment by darkdragon-001** [comment]
@dreua Update works without problems. Just the _Save as_ button stays always grayed out. The option in the main menu works though.

**Comment by dreua** [comment]
@darkdragon-001 I never noticed but it's not flatpak specific. Created a new issue.

**Comment by dreua** [comment]
@darkdragon-001 It is fixed now, thanks for reporting!

Updated flatpak to 1.5.1: https://github.com/flathub/com.github.jeromerobert.pdfarranger/pull/2
