### ISSUE TITLE
invalid literal for int() with base 10 b'612,000000'

### ISSUE THREAD

**Issue by ChinuxParibus** [jeromerobert/pdfarranger#40]
Hi, I'm using pdfarranger on Manjaro Linux. I have a PDF with 2 pages. After I selected the last page for deletion it went ok, but when I save (using either 'Save' or 'Save As' options), got this error:
`invalid literal for int() with base 10 b'612,000000'` 
It could be related to pypdf instead but I don't know, I'm not a Python developer :worried:.
Hope it can helps.

**Comment by jeromerobert** [comment]
Yes this is more likely a pypdf2 issue. There are many similar issues here:
<https://github.com/mstamy2/PyPDF2/issues?q=invalid+literal+for+int>

If this PDF is not confidential could you upload it somewhere ? So I could write a simple script and report the issue to PyPDF2.

**Comment by jeromerobert** [comment]
This PDF is not valid and this is because of that bug: <https://bugreports.qt.io/browse/QTBUG-72848>.
