### ISSUE TITLE
Remember window size 

### ISSUE THREAD

**Issue by Korodny** [jeromerobert/pdfarranger#41]
The program always opens a rather small window here (PDFA 1.1.1 on Debian Testing XFCE) that shows only eight thumbnails. I always have to resize it to something more useful before I can start working on a PDF.

Request: Have PDF Arranger remember the window's size and the maximised status,

(btw. awesome job on the update - PDF Shuffler with GTK3 and proper Shift-Click? Awesome, thanks! )

**Comment by jeromerobert** [comment]
+1

https://wiki.gnome.org/HowDoI/SaveWindowState
