### ISSUE TITLE
Please add keybindings

### ISSUE THREAD

**Issue by madduck** [jeromerobert/pdfarranger#52]
Please add the normal keybindings to quit, save-as, zoom, etc.

**Comment by madduck** [comment]
Wondering if this is still on the radar, @jeromerobert ?

**Comment by jeromerobert** [comment]
@madduck Done in the commit which closed that issue.

**Comment by madduck** [comment]
Okay, I guess I am missing something here. I don't see any keybindings. Also, hitting e.g. `ctrl+s` while on the "Save" menu item, does not assign them. What do I need to do to get those working?

**Comment by jeromerobert** [comment]
* Do you see keybinding in the menu like this:
![sc](https://user-images.githubusercontent.com/160365/62621062-4090d580-b91b-11e9-8be8-1d0db534b867.png)
* When running from a shell do you get any error message or python stack trace ?
* Which version of pdfarranger is it ?

**Comment by jeromerobert** [comment]
> does not assign them

I think it's no longer possible to assign an accelerator to a menu. See:
https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-can-change-accels

(Yet the those I assigned programmatically should work).

**Comment by madduck** [comment]
>     * Which version of pdfarranger is it ?

1.1.1, and I am confused, because the Changelog says 0.7 is latest, but `setup.py` has 1.3.0. I assume I'm running a massively outdated version, will upgrade, and thank you for your patience thus far!

**Comment by jeromerobert** [comment]
My fault. I should have removed this ChangeLog when I forked. This is now done.
