### ISSUE TITLE
Switch to Gtk.Application

### ISSUE THREAD

**Issue by jeromerobert** [jeromerobert/pdfarranger#55]
Working on #52 and #44 I have the feeling that pdfarranger should first use the UI action concept. It should be straightforward to introduce Gtk.Action but it's [deprecated](https://python-gtk-3-tutorial.readthedocs.io/en/latest/menus.html) so I would prefer to invest time on [Gtk.Application](https://python-gtk-3-tutorial.readthedocs.io/en/latest/application.html). This looks like a somehow intrusive and long work so this issue, #52 and #44 will probably remain open for a while.

**Comment by dreua** [comment]
Sounds good to me, let me know if I can be of any assistance!

As a side note, I think it might be a good idea to break the 1300 line beast that pdfarranger.py currently is down into smaller pieces. What do you think?

**Comment by jeromerobert** [comment]
> As a side note, I think it might be a good idea to break the 1300 line beast that pdfarranger.py
> currently is down into smaller pieces. What do you think?

I agree it's a bit hard to read but I think the main issue is the size of the `PdfArranger` class, not the size of the `pdfarranger.py` file. Unless I'm wrong introducing a `Gtk.Application` class should help because we'll have actions in a class and GUI layout in an other one. Anyway once implemented move the application file to a new file should be easy.

**Comment by jeromerobert** [comment]
@dreua finally that did not help to make the code clearer. I think we should create an IconView class, this would the PdfArranger thiner.

**Comment by dreua** [comment]
@jeromerobert I disagree, I think the code became clearer in many places, thank you for your ongoing maintenance!
