### ISSUE TITLE
Keep original metadata

### ISSUE THREAD

**Issue by City-busz** [jeromerobert/pdfarranger#57]
When I save edited PDF documents, the original metadata is lost. There is no way to keep the original title, author, keywords, creation date etc. It would be a nice feature to keep these metadata on save/export, or even allow to edit these fields.

**Comment by jeromerobert** [comment]
From https://stackoverflow.com/questions/46849733/change-metadata-of-pdf-file-with-pypdf2 this should be easy to implement:

```python
from PyPDF2 import PdfFileReader, PdfFileWriter

fin = open('source.pdf', 'rb')
reader = PdfFileReader(fin)

writer.appendPagesFromReader(reader)
metadata = reader.getDocumentInfo()
writer.addMetadata(metadata)

# Write your custom metadata here:
writer.addMetadata({
    '/Some': 'Example'
})

fout = open('result.pdf', 'wb')
writer.write(fout)

fin.close()
fout.close()
