### ISSUE TITLE
Install by hand in Xenial program fails to start

### ISSUE THREAD

**Issue by melodie11** [jeromerobert/pdfarranger#58]
Hello,

when trying to start the program from within the menus (lxde menus), I get:

"Fichier d'entrée de bureau invalide : '/home/melodie/.local/share/applications/pdfarranger.desktop'".

When trying to start it from a console, invoking an argument:
$ pdfarranger sysadd2.pdf 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2299, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'pdfarranger.pdfarranger' has no attribute 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/melodie/.local/bin/pdfarranger", line 11, in <module>
    load_entry_point('pdfarranger==1.1.1', 'console_scripts', 'pdfarranger')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2301, in resolve
    raise ImportError(str(exc))
ImportError: module 'pdfarranger.pdfarranger' has no attribute 'main'
$

I used the howto from the main page to install:
"On Debian based distributions:

sudo apt-get install python3-distutils-extra python3-wheel python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-poppler-0.18 python3-setuptools
"
 and

"pip3 install --user -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt"

How can I fix it?

**Comment by jeromerobert** [comment]
@melodie11 sorry I broke the launcher several days ago. It should work now.

**Comment by melodie11** [comment]
Hello, so how should I proceed now? Because:

pip3 install --user -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'

?

**Comment by jeromerobert** [comment]
I didn't bump the pip version because it's still in development so you have to force the installation. I guess that adding `--upgrade` will be enough:

```
pip install --upgrade --user -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt
```

else try a mixture of the flags from https://stackoverflow.com/questions/19548957/can-i-force-pip-to-reinstall-the-current-version

**Comment by melodie11** [comment]
Hi, I tried all of this yesterday, didn't work, so I removed it all in order to try again the next day. That would be this evening. The series, still a good thrill continues ^^


"$ sudo aptitude install python3-distutils-extra python3-wheel python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-poppler-0.18 python3-setuptools
python3-gi est déjà installé avec la version demandée (3.20.0-0ubuntu1)
gir1.2-gtk-3.0 est déjà installé avec la version demandée (3.18.306-1ubuntu3.4)
python3-gi est déjà installé avec la version demandée (3.20.0-0ubuntu1)
gir1.2-gtk-3.0 est déjà installé avec la version demandée (3.18.306-1ubuntu3.4)
Les NOUVEAUX paquets suivants vont être installés :
  gir1.2-poppler-0.18 python3-distutils-extra python3-gi-cairo python3-setuptools{b} python3-wheel 
0 paquets mis à jour, 5 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de télécharger 176 ko d'archives. Après dépaquetage, 870 ko seront utilisés.
Les paquets suivants ont des dépendances non satisfaites :
 python3-setuptools : Dépend: python3-pkg-resources (= 20.7.0-1) mais 33.1.1-1+certbot~xenial+1 est installé.
Les actions suivantes permettront de résoudre ces dépendances :
     Conserver les paquets suivants dans leur version actuelle :
1)     python3-setuptools [Non installé]                        
Accepter cette solution ? [Y/n/q/?] "

Or, 
"$ sudo aptitude update && sudo aptitude install python3-distutils-extra python3-wheel python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-poppler-0.18 python3-setuptools python3-pkg-resources
Atteint http://bouyguestelecom.ubuntu.lafibre.info/ubuntu xenial InRelease
Atteint http://bouyguestelecom.ubuntu.lafibre.info/ubuntu xenial-updates InRelease
Atteint http://bouyguestelecom.ubuntu.lafibre.info/ubuntu xenial-security InRelease
Atteint http://bouyguestelecom.ubuntu.lafibre.info/ubuntu xenial-backports InRelease
                                    
python3-gi est déjà installé avec la version demandée (3.20.0-0ubuntu1)
gir1.2-gtk-3.0 est déjà installé avec la version demandée (3.18.306-1ubuntu3.4)
python3-pkg-resources est déjà installé avec la version demandée (33.1.1-1+certbot~xenial+1)
python3-gi est déjà installé avec la version demandée (3.20.0-0ubuntu1)
gir1.2-gtk-3.0 est déjà installé avec la version demandée (3.18.306-1ubuntu3.4)
python3-pkg-resources est déjà installé avec la version demandée (33.1.1-1+certbot~xenial+1)
Les NOUVEAUX paquets suivants vont être installés :
  gir1.2-poppler-0.18 python3-distutils-extra python3-gi-cairo 
  python3-setuptools{b} python3-wheel 
0 paquets mis à jour, 5 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de télécharger 176 ko d'archives. Après dépaquetage, 870 ko seront utilisés.
Les paquets suivants ont des dépendances non satisfaites :
 python3-setuptools : Dépend: python3-pkg-resources (= 20.7.0-1) mais 33.1.1-1+certbot~xenial+1 est installé.
Les actions suivantes permettront de résoudre ces dépendances :
     Conserver les paquets suivants dans leur version actuelle :
1)     python3-setuptools [Non installé]                        
Accepter cette solution ? [Y/n/q/?] 
"

I'll try that one. 

no no no no 
http://www.servan-schreiber.net/5h30/assets/uploads/2019/03/Capture-d%E2%80%99%C3%A9cran-2019-03-14-%C3%A0-12.52.32.png

??

"Les actions suivantes permettront de résoudre ces dépendances :

     Réinstaller à une version antérieure les paquets suivants :                   
1)     python3-pkg-resources [33.1.1-1+certbot~xenial+1 (now) -> 20.7.0-1 (xenial)]"

Let's give it a try.
"Y"

"Accepter cette solution ? [Y/n/q/?] 
Les paquets suivants vont être RÉINSTALLÉS à une VERSION ANTÉRIEURE :
  python3-pkg-resources 
Les NOUVEAUX paquets suivants vont être installés :
  gir1.2-poppler-0.18 python3-distutils-extra python3-gi-cairo python3-setuptools python3-wheel 
0 paquets mis à jour, 5 nouvellement installés, 1 remis à une version antérieure, 0 à enlever et 0 non mis à jour.
Il est nécessaire de télécharger 255 ko d'archives. Après dépaquetage, 769 ko seront utilisés.
Voulez-vous continuer ? [Y/n/?] " Y 

That went through. Now the final,
sudo apt install python-pip python-all-dev python-wheel

then:
pip install --upgrade --user -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt

"$ pip install --upgrade --user -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt
Collecting https://github.com/jeromerobert/pdfarranger/zipball/master (from -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt (line 1))
  Downloading https://github.com/jeromerobert/pdfarranger/zipball/master
     - 952kB 15.0MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-OdE5Gv-build/setup.py", line 27, in <module>
        from DistUtilsExtra.command import *
    ImportError: No module named DistUtilsExtra.command
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-OdE5Gv-build/
You are using pip version 8.1.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command."

what the pinguin?? :-(

"$ pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 605kB/s 
Installing collected packages: pip
Successfully installed pip-8.1.1
You are using pip version 8.1.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command."

what do all the pinguins??? >:-[  

…
$ pip install --upgrade pip
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
[melodie@bento64:~]
$ pip install --upgrade --user -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
…

and that's all folk!

o/

**Comment by melodie11** [comment]
Hi, I tried all of this yesterday, didn't work, so I removed it all in order to try again the next day. That would be this evening. The series, still a good thrill continues ^^


"$ sudo aptitude install python3-distutils-extra python3-wheel python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-poppler-0.18 python3-setuptools
python3-gi est déjà installé avec la version demandée (3.20.0-0ubuntu1)
gir1.2-gtk-3.0 est déjà installé avec la version demandée (3.18.306-1ubuntu3.4)
python3-gi est déjà installé avec la version demandée (3.20.0-0ubuntu1)
gir1.2-gtk-3.0 est déjà installé avec la version demandée (3.18.306-1ubuntu3.4)
Les NOUVEAUX paquets suivants vont être installés :
  gir1.2-poppler-0.18 python3-distutils-extra python3-gi-cairo python3-setuptools{b} python3-wheel 
0 paquets mis à jour, 5 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de télécharger 176 ko d'archives. Après dépaquetage, 870 ko seront utilisés.
Les paquets suivants ont des dépendances non satisfaites :
 python3-setuptools : Dépend: python3-pkg-resources (= 20.7.0-1) mais 33.1.1-1+certbot~xenial+1 est installé.
Les actions suivantes permettront de résoudre ces dépendances :
     Conserver les paquets suivants dans leur version actuelle :
1)     python3-setuptools [Non installé]                        
Accepter cette solution ? [Y/n/q/?] "

Or, 
"$ sudo aptitude update && sudo aptitude install python3-distutils-extra python3-wheel python3-gi python3-gi-cairo gir1.2-gtk-3.0 gir1.2-poppler-0.18 python3-setuptools python3-pkg-resources
Atteint http://bouyguestelecom.ubuntu.lafibre.info/ubuntu xenial InRelease
Atteint http://bouyguestelecom.ubuntu.lafibre.info/ubuntu xenial-updates InRelease
Atteint http://bouyguestelecom.ubuntu.lafibre.info/ubuntu xenial-security InRelease
Atteint http://bouyguestelecom.ubuntu.lafibre.info/ubuntu xenial-backports InRelease
                                    
python3-gi est déjà installé avec la version demandée (3.20.0-0ubuntu1)
gir1.2-gtk-3.0 est déjà installé avec la version demandée (3.18.306-1ubuntu3.4)
python3-pkg-resources est déjà installé avec la version demandée (33.1.1-1+certbot~xenial+1)
python3-gi est déjà installé avec la version demandée (3.20.0-0ubuntu1)
gir1.2-gtk-3.0 est déjà installé avec la version demandée (3.18.306-1ubuntu3.4)
python3-pkg-resources est déjà installé avec la version demandée (33.1.1-1+certbot~xenial+1)
Les NOUVEAUX paquets suivants vont être installés :
  gir1.2-poppler-0.18 python3-distutils-extra python3-gi-cairo 
  python3-setuptools{b} python3-wheel 
0 paquets mis à jour, 5 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de télécharger 176 ko d'archives. Après dépaquetage, 870 ko seront utilisés.
Les paquets suivants ont des dépendances non satisfaites :
 python3-setuptools : Dépend: python3-pkg-resources (= 20.7.0-1) mais 33.1.1-1+certbot~xenial+1 est installé.
Les actions suivantes permettront de résoudre ces dépendances :
     Conserver les paquets suivants dans leur version actuelle :
1)     python3-setuptools [Non installé]                        
Accepter cette solution ? [Y/n/q/?] 
"

I'll try that one. 

no no no no 
http://www.servan-schreiber.net/5h30/assets/uploads/2019/03/Capture-d%E2%80%99%C3%A9cran-2019-03-14-%C3%A0-12.52.32.png

??

"Les actions suivantes permettront de résoudre ces dépendances :

     Réinstaller à une version antérieure les paquets suivants :                   
1)     python3-pkg-resources [33.1.1-1+certbot~xenial+1 (now) -> 20.7.0-1 (xenial)]"

Let's give it a try.
"Y"

"Accepter cette solution ? [Y/n/q/?] 
Les paquets suivants vont être RÉINSTALLÉS à une VERSION ANTÉRIEURE :
  python3-pkg-resources 
Les NOUVEAUX paquets suivants vont être installés :
  gir1.2-poppler-0.18 python3-distutils-extra python3-gi-cairo python3-setuptools python3-wheel 
0 paquets mis à jour, 5 nouvellement installés, 1 remis à une version antérieure, 0 à enlever et 0 non mis à jour.
Il est nécessaire de télécharger 255 ko d'archives. Après dépaquetage, 769 ko seront utilisés.
Voulez-vous continuer ? [Y/n/?] " Y 

That went through. Now the final,
sudo apt install python-pip python-all-dev python-wheel

then:
pip install --upgrade --user -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt

"$ pip install --upgrade --user -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt
Collecting https://github.com/jeromerobert/pdfarranger/zipball/master (from -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt (line 1))
  Downloading https://github.com/jeromerobert/pdfarranger/zipball/master
     - 952kB 15.0MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-OdE5Gv-build/setup.py", line 27, in <module>
        from DistUtilsExtra.command import *
    ImportError: No module named DistUtilsExtra.command
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-OdE5Gv-build/
You are using pip version 8.1.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command."

what the pinguin?? :-(

"$ pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 605kB/s 
Installing collected packages: pip
Successfully installed pip-8.1.1
You are using pip version 8.1.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command."

what do all the pinguins??? >:-[  

…
$ pip install --upgrade pip
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
[melodie@bento64:~]
$ pip install --upgrade --user -r https://raw.githubusercontent.com/jeromerobert/pdfarranger/master/requirements.txt
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
…

and that's all folk!

o/

**Comment by jeromerobert** [comment]
Sous Debian et ses dérivées `pip` est relatif à python2. Il faut que tu utilises `pip3`.

**Comment by jeromerobert** [comment]
Et avec `pip install --upgrade pip` tu as installé `pip` python2 dans `~/.local/bin` mais il n'est pas dans le `PATH`. Tu utilises `/usr/bin/pip` et il n'est pas compatible avec le pip que tu viens d'installer. (mais ca n'a rien a voir avec pdfarranger).
