### ISSUE TITLE
Undo/Redo support

### ISSUE THREAD

**Issue by sojusnik** [jeromerobert/pdfarranger#59]
This app would greatly benefit from a undo/redo function.

**Comment by jeromerobert** [comment]
Roadmap:
* List all actions
* Split the list between actions which need to be undoable and those who do not need to be undoable (those who do not modify the document)
* For each undoable action, move the current code to a `class UndoReadoAction` with:
    * a `do_action` method
    * an `undo_action` method
    * every attributs needed to run `undo_action`
* Add redo and undo actions and menus, which stack/unstack `UndoReadoAction` instances

This is a too long and intrusive work for the next release so I set the low priority tag.

**Comment by jeromerobert** [comment]
Actions to undo:
* Add pages
* Rotate
* Crop
* Delete
* Reverse order

**Comment by dreua** [comment]
Nice, the code looks good to me! Will give it a try asap.

**Comment by dreua** [comment]
Minor issue: Undo and Redo resets the zoom level

**Comment by dreua** [comment]
Larger issue: Redo does not work for me. (Tried it with moving and deleting single and multiple pages. It seems to have no effect except for the zoom level.)

**Comment by jeromerobert** [comment]
@dreua thanks for the tests, I'm going to fix both issues.

**Comment by jeromerobert** [comment]
I fixed the zoom issue. About redo it's worse than what you describe. Sometime it works, and sometime the whole model become broken. Even the first undo may not work. I can play a while with undo/redo with no issue then the pages get moved at random positions.

**Comment by jeromerobert** [comment]
@dreua It should work now
