### ISSUE TITLE
Space at the right border

### ISSUE THREAD

**Issue by sojusnik** [jeromerobert/pdfarranger#60]
In comparison to the left side, the space from the preview thumbnail to the right border of the app is much bigger, as shown [here](https://mega.nz/#!jtZH2K4b!t_4BBpT36YbsIYvDx2kU6TWDJVyooFEyKXWtyAN5Sc8). Ideally, this distance should be equal on both sides. This would ensure a consistent look.

Happens with the 1.1.1 version on Ubuntu 18.10.

**Comment by jeromerobert** [comment]
What about having equal distance between borders and all thumbnail ? I mean a kind of justified layout.
