### ISSUE TITLE
Correct a German translation

### ISSUE THREAD

**Issue by sojusnik** [jeromerobert/pdfarranger#61]
The German translation for "Export selection..." is currently "Markierte Seiten Exportieren …". It should be changed to "Markierte Seiten exportieren …" = the last word should start with a small letter.

**Comment by dreua** [comment]
Hey sojusnik,
I agree, that is a typo. Would you like to make a pull request with the change? I can test or assist you if needed.

**Comment by jeromerobert** [comment]
I think it does not make sense to do a PR for a so trivial issue. I'll push it soon.
