### ISSUE TITLE
error on startup, cannot use any button

### ISSUE THREAD

**Issue by zocker-160** [jeromerobert/pdfarranger#63]
when I pull the master and try to launch it I get this:

```
$ python3 -m pdfarranger
Traceback (most recent call last):
  File "/home/arbeit/Programmierkram/GitHub/pdfarranger/pdfarranger/pdfarranger.py", line 396, in do_activate
    self.__create_actions()
  File "/home/arbeit/Programmierkram/GitHub/pdfarranger/pdfarranger/pdfarranger.py", line 204, in __create_actions
    ('quit', self.on_quit),
TypeError: Item 0: argument self: Expected Gio.ActionEntry, but got tuple
```

all buttons are greyed out all the time and makes it unusable

OS is Ubuntu 18.04 with Python 3.6.7
I have the same issue on a openSUSE Leap 15 system

>Oh, and I just realized that we should also try to fix the current master. Could you provide some information what's wrong?

_Originally posted by @dreua in https://github.com/jeromerobert/pdfarranger/pull/62#issuecomment-477995183_

**Comment by jeromerobert** [comment]
Could you give the output of `dpkg -l python3-gi gir1.2-gtk-3.0 libgtk-3-0` ?

**Comment by jeromerobert** [comment]
This might be related to https://gitlab.gnome.org/GNOME/pygobject/issues/29

**Comment by zocker-160** [comment]
sure this is my output:
```
$ dpkg -l python3-gi gir1.2-gtk-3.0 libgtk-3-0
Gewünscht=Unbekannt/Installieren/R=Entfernen/P=Vollständig Löschen/Halten
| Status=Nicht/Installiert/Config/U=Entpackt/halb konFiguriert/
         Halb installiert/Trigger erWartet/Trigger anhängig
|/ Fehler?=(kein)/R=Neuinstallation notwendig (Status, Fehler: GROSS=schlecht)
||/ Name                           Version              Architektur          Beschreibung
+++-==============================-====================-====================-=================================================================
ii  gir1.2-gtk-3.0:amd64           3.22.30-1ubuntu2     amd64                GTK+ graphical user interface library -- gir bindings
ii  libgtk-3-0:amd64               3.22.30-1ubuntu2     amd64                GTK+ graphical user interface library
ii  python3-gi                     3.26.1-2ubuntu1      amd64                Python 3 bindings for gobject-introspection libraries
```

**Comment by zocker-160** [comment]
btw it would be handy to change in the readme `python -m pdfarranger` into `python3 -m pdfarranger` because it doesn't work with python 2.

```
$ python --version
Python 2.7.15rc1
$ python3 --version
Python 3.6.7
```

**Comment by jeromerobert** [comment]
https://gitlab.gnome.org/GNOME/pygobject/issues/29 as been fixed in python3-gi 3.29 and I have 3.30. Example of workaround: https://github.com/MicahCarrick/python-bloatpad/blob/master/bloatpad.py#L106

**Comment by jeromerobert** [comment]
@zocker-160  could you test 0a01a7f before I merge it into master ?

(or anyone else having python3-gi < 2.29.2)

**Comment by zocker-160** [comment]
can confirm no more error on startup and I can use it as intended.
nice!
