### ISSUE TITLE
Feature Request: Add basic metadata editing

### ISSUE THREAD

**Issue by blueorignal** [jeromerobert/pdfarranger#68]
Thank you for a great tool. It's simple to use, effective and looks good to boot.

One think that I believe would be of great value to users is the ability to edit the metadata of the PDF, specifically the Title and Author fields (but other fields as well).

This can be presently be done with 3rd party tools such as exiftools, but it would be fantastic if the capability was directly built into the tool.

**Comment by jeromerobert** [comment]
Ok this just about to create a form to edit https://pythonhosted.org/PyPDF2/DocumentInformation.html#PyPDF2.pdf.DocumentInformation

Related issue to #57

**Comment by jeromerobert** [comment]
#59 should be fixed before working on that issue.

**Comment by jeromerobert** [comment]
And as there will be a QPDF version of pdfarranger we'll also need https://pikepdf.readthedocs.io/en/latest/tutorial/metadata.html
