### ISSUE TITLE
Saving not possible

### ISSUE THREAD

**Issue by fabaff** [jeromerobert/pdfarranger#71]
There seems to be an issue when you want to save a file.

```bash
createStringObject should have str or unicode arg
```

Dependencies are coming out of the Fedora Package Collection.

**Comment by jeromerobert** [comment]
This is either a bug in PyPDF2 or in the PDF file. I would need the PDF file.

**Comment by fabaff** [comment]
This is one that is not working.

[5995515b9e24f-MYQUserManual.pdf](https://github.com/jeromerobert/pdfarranger/files/3164230/5995515b9e24f-MYQUserManual.pdf)

**Comment by jeromerobert** [comment]
Ok this is a regression introduced when fixing #57. There will be a 1.2.1 soon.
