### ISSUE TITLE
qpdf/pikepdf instead of PyPDF2

### ISSUE THREAD

**Issue by sojusnik** [jeromerobert/pdfarranger#74]
Did you think about using [qpdf](https://github.com/qpdf/qpdf) or its python pendant [pikepdf](https://github.com/pikepdf/pikepdf#features) instead of PyPDF2? [Here](https://github.com/pikepdf/pikepdf#features) is a comparison.

**Comment by jeromerobert** [comment]
Ok let's give it a try. I would like first to isolate PyPDF2 stuff to an abstract class so we could use both PyPDF2 and pikepdf.

**Comment by jeromerobert** [comment]
Everything related to PyPDF2 seems to be already isolated in <https://github.com/jeromerobert/pdfarranger/blob/master/pdfarranger/pdfarranger.py#L671>, so this should be already easy to implement.

In a first time I would like PikePDF to be optional. It should be used if available and fall back to PyPDF2 if not. It should be declared optional in setup.py thanks to <https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies>. This way we could wait to work on PikePDF support on Windows.
