### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by fabaff** [jeromerobert/pdfarranger#75]
Installation is done with `pip3 install --user .`. At  least "Zoon in" (Vergrössern) is missing and thee are encoding error in the console output. 

```bash
$ LANG=de_DE pdfarranger
[...]
(pdfarranger:31002): Gtk-WARNING **: 10:51:15.347: Failed to set text 'Dokument \xf6ffnen und zum bereits ge\xf6ffneten Dokument hinzuf\xfcgen' from markup due to error parsing markup: Fehler in Zeile 1, Zeichen 71: Ung�ltiger UTF-8-kodierter Text im Namen ? �Dokument \xf6ffnen und zum bereits ge\xf6ffneten Dokument hinzuf\xfcgen� ist nicht g�ltig
[...]
```

**Comment by jeromerobert** [comment]
`LANG=de_DE.UTF-8 pdfarranger` work as expected.

From [the GTK FAQ](https://developer.gnome.org/gtk3/stable/gtk-question-index.html), to support non-UTF-8 charsets, I have to call [`bind_textdomain_codeset`](http://man7.org/linux/man-pages/man3/bind_textdomain_codeset.3.html) but it's not available through [python](https://docs.python.org/3/library/locale.html).

To be continued...
