### ISSUE TITLE
Provide software as Copr repo

### ISSUE THREAD

**Issue by rmeissn** [jeromerobert/pdfarranger#77]
Fedora (and other RPM based distros) has the option to install third party software from COPR repositories, very similar to Ubuntus PPAs - https://copr.fedorainfracloud.org/coprs/
It would be really handy to provide the package as a COPR repo, as the current Fedora 30 version of pdfshuffler is broken (see https://bugzilla.redhat.com/show_bug.cgi?id=1708993 ) and no update has been released so far. COPR makes it very easy to install third party packages (instead of having each user to handle all the setup steps).

This request is related to #37. In my opinion it's more efficient (space + speed of execution) to provide something as a COPR instead of a flatpak, but flatpak has way better portability to other OSs.

**Comment by jeromerobert** [comment]
@fabaff is working on packaging pdfarranger 1.2 for fedora. See:
* https://bugzilla.redhat.com/show_bug.cgi?id=1651404
* https://bugzilla.redhat.com/show_bug.cgi?id=1679361

**Comment by dreua** [comment]
https://copr.fedorainfracloud.org/coprs/dreua/python-pdfarranger/

**Comment by dreua** [comment]
Ok, that was too optimistic. Building and installing worked on my pc but it seems there are dependencies missing for copr.
Spec file is here: https://github.com/dreua/pdfarranger-rpmspec

**Comment by dreua** [comment]
Except for the icon, everything seems to be working fine :)

**Comment by dreua** [comment]
Fixed icon and translations in version 1.2.1-4.

**Comment by dreua** [comment]
I also went ahead and submitted a [review request for Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1711611).
@fabaff I hope you don't mind. Please feel free to take over if you want or in case I don't get sponsored as packager.

**Comment by fabaff** [comment]
Well, that's life. I'm happy about every package that someone else looks after.

**Comment by jeromerobert** [comment]
Closing thanks to dreua

**Comment by dreua** [comment]
Should we mention the copr in the readme?

**Comment by jeromerobert** [comment]
I'm wondering. I think few github projects do that. If we do that, we'll have to list all packages. There are already sites doing this like: https://pkgs.org/download/pdfarranger. Your Copr is not yet listed but https://rpmsphere.github.io is. I did list packages for k4dirstat (https://bitbucket.org/jeromerobert/k4dirstat/wiki/Home) but I don't know if that is that useful. I'll sleep on it.

**Comment by jeromerobert** [comment]
@dreua
* https://github.com/jeromerobert/pdfarranger/wiki/Binary-packages
* https://github.com/jeromerobert/pdfarranger/commit/386aad1

**Comment by dreua** [comment]
@rmeissn Since pdfarranger is in the official repositories since Fedora 30, is there still a use case for the copr repository? (I don't want to keep updating a copr that nobody actually uses.)

**Comment by rmeissn** [comment]
@dreua As pdfarranger is now part of the official Fedora repos, I don't see a use-case for a copr repo anymore. Many thanks for providing it officially!
