### ISSUE TITLE
Official windows builds

### ISSUE THREAD

**Issue by arisboch** [jeromerobert/pdfarranger#83]
Could you release builds for Windows either here or elsewhere, please? I can't seem to get it to work on MSYS2 and not everyone knows enough to do that?

**Comment by jeromerobert** [comment]
They are already available in the [release section](https://github.com/jeromerobert/pdfarranger/releases)

**Comment by arisboch** [comment]
> They are already available in the [release section](https://github.com/jeromerobert/pdfarranger/releases)

Sry, I overlooked that, thanks for the link.
