### ISSUE TITLE
Feature request: split page spreads into pages

### ISSUE THREAD

**Issue by antoneliasson** [jeromerobert/pdfarranger#86]
When scanning books I usually scan a two-page spread at a time. This results in a PDF where the first PDF page is book page 2+3, the second PDF page is book page 4+5 etc. (counting the book cover as page 1). I would like to automate the task of cropping the spreads into two equal sized halves.

This could be implemented with the current feature set like this:

For each PDF page (selected):
1. Duplicate it into two copies
2. Crop the first copy with a 50 % right margin.
3. Crop the second copy with a 50 % left margin.

**Comment by jeromerobert** [comment]
Note that the resulting document will be twice as big as the original one because crop does not remove any content (it just hide).
