### ISSUE TITLE
New UI look & feel (header bar, symbolic icons)

### ISSUE THREAD

**Issue by jeromerobert** [jeromerobert/pdfarranger#87]
[GtkImageMenuItem](https://developer.gnome.org/gtk3/stable/GtkImageMenuItem.html) is deprecated. It should be replaced by [GMenu](https://developer.gnome.org/GMenu). This is needed for [GTK4 migration](https://developer.gnome.org/gtk4/stable/gtk-migrating-3-to-4.html) (which is not an emergency).

Removing `GtkImageMenuItem` mean removing [stock items](https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html) which mean that many menu items won't be translated by GTK anymore. So all `.po` files needs to be updated.

**Comment by jeromerobert** [comment]
Translations for stock items can be found here:
* https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/gtk/deprecated/gtkstock.h
* https://gitlab.gnome.org/GNOME/gtk/blob/gtk-3-24/po/

**Comment by jeromerobert** [comment]
I was already not fond of removing icons from menus but looking at other GTK applications I think I have to go even further. Even Meld has already redesigned its GUI so it now looks like evince, gedit and many other gnome/GTK apps. I personally don't like such look & feel but this is mostly subjective and resistance against Gnome/GTK guidelines is futile. So here is the roadmap:

* Replace the [menu bar](https://developer.gnome.org/hig/stable/menu-bars.html.en) by a [GtkHeaderBar](https://developer.gnome.org/hig/stable/header-bars.html.en)
* Merge all menus in a single one located on the left of the header bar. This new menu will be a GMenu.
* Replace all icons by their symbolic version
* Move toolbar buttons to the new header bar

**Comment by onny** [comment]
Just as a reference how nice this could look:
![image](https://user-images.githubusercontent.com/757752/69451048-c3b92880-0d5e-11ea-8aac-9f28b1fb24cb.png)
(see https://github.com/onny/pdfmod3)

**Comment by Amr-Ibra** [comment]
An easy start is to just replace the icons to their symbolic versions. The legacy full-coloured icons don't scale well in Hi DPI displays.

**Comment by jeromerobert** [comment]
![pdfarranger-newlook](https://user-images.githubusercontent.com/160365/77254915-3205ed00-6c64-11ea-932b-0548c5dd3dd4.png)
I moved the toolbar button to the header bar (in a dirty dev branch). I was thinking of creating a single main menu but now I'm thinking we have too many actions for that. I will probably create 2:
- a main menu which will receive file, view and help menus
- an edit menu (same as the current one)

What's your opinion ? Does it feel "gnomish" or should I have less menus or icons in the header bar ?

**Comment by onny** [comment]
Wow thanks for this nice concept :) I was already checking today for some updates on this ;)
This is was ``evince`` is doing:
![2020-03-22-202438_grim](https://user-images.githubusercontent.com/757752/77258518-5faa6080-6c7b-11ea-8e72-6572837dcf29.png)
Show edit menu:
![2020-03-22-202453_grim](https://user-images.githubusercontent.com/757752/77258516-5de09d00-6c7b-11ea-87d8-b1b5ffaa8bea.png)
Personally I prefer ``gedit`` which is even simpler and cleaner:
![2020-03-22-202731_grim](https://user-images.githubusercontent.com/757752/77258553-91bbc280-6c7b-11ea-8677-6f3f9099031e.png)
But this might not fit the need in this case. At least the bold open and save option is really good here in my opinion.

**Comment by kbengs** [comment]
I think that looks nice. Also a display for total number of pages would be good to have IMO. Would it have room somewhere? It would help user to see if things are going as planned. (if adding pages -> number increase..)
