### ISSUE TITLE
Truncate long pdf filename with ellipsis

### ISSUE THREAD

**Issue by onny** [jeromerobert/pdfarranger#92]
Hey,
thanks for this nice tool. I'm really looking forward to the GtkHeaderBar rework :)
Here's an issue I encountered today:
![image](https://user-images.githubusercontent.com/757752/61135388-c870f480-a4c1-11e9-82e6-6bd9abf7e73c.png)
Would be better to abbreviate long pdf filenames in the page previews.

Best regards,
Jonas

**Comment by jeromerobert** [comment]
* Change that property: <https://lazka.github.io/pgi-docs/index.html#Gtk-3.0/classes/CellRendererText.html#Gtk.CellRendererText.props.ellipsize>
* To get the `CellRendererText` use: <https://lazka.github.io/pgi-docs/index.html#Gtk-3.0/classes/CellLayout.html#Gtk.CellLayout.get_cells>
* The `CellRendererText` instance is created by <https://lazka.github.io/pgi-docs/index.html#Gtk-3.0/classes/IconView.html#Gtk.IconView.set_text_column>.

This will looks like this:
![ellipsis](https://user-images.githubusercontent.com/160365/61169360-995b9100-a55c-11e9-930b-cdaadaedc1b8.png)
